import QtQuick

// The UI's text, in one place.
//
// Not Qt's own translation machinery: that wants .ts files compiled to .qm at
// build time, and this plugin is loaded from a directory of QML with nothing
// to build it. A plain table is also inspectable — a missing key shows up as
// the key itself rather than as blank space.
//
// Instantiated per root component (console, HUD, bar module) and handed down
// to child views as a property, because a plugin folder has no import path of
// its own to hang a singleton on.
//
// Product nouns stay untranslated on purpose: wtype, XWayland, PipeWire, ggml,
// VRAM, evdev. Translating a thing you have to type into a terminal or search
// for makes it unfindable.
Item {
  id: root

  // "" follows the environment; anything else wins.
  property string lang: ""

  // English first because it is the default; the rest by their own names,
  // Latin-script ones alphabetically and then the others.
  readonly property var languages: [
    { code: "en", name: "English" },
    { code: "de", name: "Deutsch" },
    { code: "es", name: "Español" },
    { code: "fr", name: "Français" },
    { code: "vi", name: "Tiếng Việt" },
    { code: "zh", name: "简体中文" },
    { code: "ja", name: "日本語" },
    { code: "th", name: "ไทย" }
  ]

  readonly property string active: {
    if (lang && _table[lang] !== undefined) return lang
    // Qt.locale().name is like "de_DE"; the two-letter prefix is enough, and
    // a locale with no pack falls through to English rather than to nothing.
    var env = (Qt.locale().name || "en").toLowerCase().substring(0, 2)
    return _table[env] !== undefined ? env : "en"
  }

  function t(key) {
    var pack = _table[root.active] || {}
    if (pack[key] !== undefined) return pack[key]
    var base = _table.en || {}
    // The key itself, so an untranslated string is visible rather than blank.
    return base[key] !== undefined ? base[key] : key
  }

  // Same, with one substitution. Kept separate so the common case stays a
  // plain lookup.
  function tf(key, a) {
    return String(t(key)).replace("%1", a === undefined ? "" : String(a))
  }

  function nameOf(code) {
    for (var i = 0; i < languages.length; i++)
      if (languages[i].code === code) return languages[i].name
    return code
  }

  readonly property var _table: ({
    en: {
      // ---- nav
      "nav.history": "History",
      "nav.modes": "Modes",
      "nav.models": "Models",
      "nav.dictionary": "Dictionary",
      "nav.settings": "Settings",
      "lang.label": "Language",

      // ---- state
      "state.ready": "Ready",
      "state.idle": "idle",
      "state.recording": "recording",
      "state.transcribing": "transcribing",
      "state.stopped": "daemon stopped",

      // ---- setup
      "setup.prefix": "setup ",
      "setup.title": "Two more pieces to install",
      "setup.blurb": "Nothing here runs until you press it, and every step shows the exact command first. Omarchy deliberately runs nothing from inside a plugin folder, so this screen asks instead.",
      "setup.optional": "optional",
      "setup.copy": "Copy",
      "setup.run": "Run",
      "setup.recheck": "Re-check",
      "setup.hint": "or run  omavoi setup  in a terminal — same steps, same order",

      // ---- history
      "hist.none": "no takes yet — hold %1 and talk",
      "hist.yourkey": "your key",
      "hist.dropped": "dropped — ",
      "hist.audio": "audio",
      "hist.level": "level",
      "hist.decode": "decode",
      "hist.model": "model",
      "hist.language": "language",
      "hist.mode": "mode",
      "hist.injected": "injected",
      "hist.said": "model said:  ",
      "hist.post": "POST-PROCESSING",
      "hist.segments": "SEGMENT CONFIDENCE",
      "hist.copy": "Copy",
      "hist.play": "Play",

      // ---- modes
      "modes.wontfit": "needs %1 free",
      "modes.blocked": "not switched — this mode's model will not fit in VRAM right now",
      "modes.newname": "new mode name",
      "modes.here": "here",
      "modes.fallback": "fallback",
      "modes.followwin": "The mode follows the focused window",
      "modes.everytake": "Every take uses ",
      "modes.longestwins": "The longest match below wins; nothing matching falls back to default.",
      "modes.matchoff": "Window matching is off, so the lists below are configured but inert. It needs tuning per application before it earns its keep.",
      "modes.following": "following the window",
      "modes.fixed": "fixed",
      "modes.activehere": "active in this window",
      "modes.delete": "Delete mode",
      "modes.opens": "OPENS ON",
      "modes.notinuse": "not in use while the mode is fixed",
      "modes.nothing": "nothing — this mode is only reached by name",
      "modes.classph": "window class, e.g. thunderbird",
      "modes.add": "Add",
      "modes.matchhint": "Matched against the Hyprland class and title. The longest match wins.",
      "modes.s1": "1  SPEECH",
      "modes.speechsub": "what the model is told before it decodes",
      "modes.language": "language",
      "modes.langhint": "empty detects it per take; a code like en or zh is faster and steadier",
      "modes.decoderhint": "decoder hint",
      "modes.promptph": "Seeded into the model. Good for jargon it keeps mangling — a hint, not a guarantee; the dictionary is the guarantee.",
      "modes.s2": "2  RULES",
      "modes.rulessub": "deterministic · no latency",
      "modes.r.hallucinations": "hallucinations",
      "modes.r.fillers": "fillers",
      "modes.r.dictionary": "dictionary",
      "modes.r.names": "names",
      "modes.r.cjk": "CJK spacing",
      "modes.keeppunct": "keep end punctuation",
      "modes.s3": "3  LLM",
      "modes.llmsub": "optional · runs in order · a failure keeps the text it was given",
      "modes.step": "step ",
      "modes.stepsuffix": "",
      "modes.remove": "Remove",
      "modes.stepph": "Tell it to edit, not to reply.",
      "modes.nostep": "This mode has no LLM pass, so there is no prompt to write yet. Add one below and its prompt appears here, editable, with a usable default already in it.",
      "modes.addstep": "+ add a step",
      "modes.nollm": "no LLM is configured — see the Models tab",
      "modes.inject.auto": "auto",
      "modes.inject.clipboard": "clipboard",
      "modes.langauto": "auto",
      "modes.s4": "4  INJECT",
      "modes.injecthint": "auto types with wtype, except in XWayland clients and known Electron apps, where it pastes instead — wtype's synthetic keycodes reach those as digits.",

      // ---- models
      "models.speech": "SPEECH",
      "models.speechsub": "audio → text · one runs",
      "models.e.vulkan": "Local · Vulkan",
      "models.e.vulkan.sub": "whisper.cpp · ggml weights · NVIDIA, AMD and Intel alike",
      "models.e.vulkan.note": "~10 MB of packages",
      "models.e.cuda": "Local · CUDA",
      "models.e.cuda.sub": "faster-whisper · ct2 weights · NVIDIA only",
      "models.e.cuda.note": "~2.2 GB of wheels",
      "models.e.api": "Remote API",
      "models.e.api.sub": "OpenAI-compatible · OpenAI, Groq, SiliconFlow, a local server",
      "models.e.api.note": "audio leaves this machine",
      "models.llmcathint": "named by a mode's step, not switched globally",
      "models.now": "RUNNING NOW",
      "models.running": "running",
      "models.notloaded": "not loaded",
      "models.cold": "cold · starts on first use",
      "models.ready": "ready",
      "models.nodaemon": "daemon not reachable — what is loaded is unknown",
      "models.stale": "The daemon is still running what it started with",
      "models.loaded": "loaded ",
      "models.configured": "configured ",
      "models.restart": "Restart daemon",
      "models.list": "MODELS · ",
      "models.formathint": "the format this engine runs",
      "models.ondisk": "already on disk",
      "models.downloading": "downloading…",
      "models.download": "Download",
      "models.use": "Use",
      "models.remove": "Remove",
      "models.ourstore": "our store",
      "models.outside": "Weights found outside %1 are used where they lie and never deleted.",
      "models.llm": "LLM",
      "models.llmsub": "text → text · any number, named by modes",
      "models.remote": "remote",
      "models.local": "local",
      "models.nokey": "no key",
      "models.usedby": "used by ",
      "models.unused": "not named by any mode — costs nothing until one does",
      "models.endpointnote": "Endpoints live under [llm.<name>] — omavoi config edit. A key never goes in the config: set its environment variable, or put it in secrets.toml.",
      "models.vram": "VRAM · ",
      "models.seg.speech": "speech model",
      "models.seg.other": "other programs",
      "models.seg.free": "free",
      "models.vramsub": "in use across the whole machine",
      "models.needs": "needs",
      "models.vramnote": "Keeping both resident is the point: a chain that loads weights per take costs seconds, not milliseconds. Overcommit and the speech model is what gets evicted — dictation goes ten times slower with nothing to say why.",

      // ---- dictionary
      "dict.rules": "rules",
      "dict.names": "names",
      "dict.blurb": "heard → meant. A decoder prompt is a hint the model may ignore; this is the guarantee. The longest key is tried first, so a shorter one it contains can never fire.",
      "dict.shadowed": "never fires — shadowed by ",
      "dict.remove": "Remove",
      "dict.namesblurb": "Write only the correct form. Names are seeded into the decoder prompt so the model produces them, and matched by sound afterwards so homophones collapse back. Matching stays off until a dry run has been looked at — it is the one thing here that can damage text that was already right.",
      "dict.matching": "matching",
      "dict.seedonly": "seed only",
      "dict.dryrun": "Dry run",
      "dict.enable": "Enable matching",
      "dict.prompt": "prompt: ",
      "dict.none": "(none)",
      "dict.addrule": "Add one with  omavoi dict add <heard> <meant>",
      "dict.addnames": "Add several at once with  omavoi names add <name> <name> …",

      // ---- settings
      "set.ptt": "push to talk",
      "set.toggle": "toggle",
      "set.dwell.always": "always",
      "set.dwell.changed": "changed",
      "set.dwell.never": "never",
      "set.hotkey": "HOTKEY",
      "set.key": "key",
      "set.behaviour": "behaviour",
      "set.hotkeynote": "Read from evdev, below xkb, so the key stays where it physically is even if your layout remaps it. A modifier cannot be bound in Hyprland instead: pressing one changes the modmask, which fires the release binding at once and records a 0.0s take.",
      "set.audio": "AUDIO",
      "set.preroll": "pre-roll",
      "set.prerollwhy": "Audio kept from before the key went down. Lower it and the first syllable starts going missing while PipeWire opens the stream.",
      "set.tail": "tail",
      "set.warnbelow": "warn below",
      "set.maxtake": "max take",
      "set.hud": "HUD",
      "set.keepup": "keep the result up",
      "set.hudnote": "\"changed\" is the default: a dwell you always pay for turns into noise the moment you dictate two sentences in a row, but a silent correction you never saw is worse.",
      "set.notifications": "notifications",
      "set.on": "on",
      "set.off": "off",
      "set.history": "HISTORY",
      "set.keepaudio": "keep audio for",
      "set.takes": " takes",
      "set.historynote": "Stored audio is what makes re-running a take on another model, and the names dry run, possible. Set it to 0 and those go away with it.",
      "set.privacy": "WHERE YOUR VOICE GOES",
      "set.neverleaves": "Audio never leaves this machine",
      "set.privacynote": "Speech runs on the local GPU in every mode. A mode whose LLM step is a remote model does send the transcribed text out — the Modes tab shows which ones have a step at all.",
      "set.editconfig": "Edit config",
      "set.restart": "Restart daemon",
      "set.configpath": "everything here is  ~/.config/omavoi/config.toml"
    },
    zh: {
      // ---- nav
      "nav.history": "历史",
      "nav.modes": "模式",
      "nav.models": "模型",
      "nav.dictionary": "词典",
      "nav.settings": "设置",
      "lang.label": "语言",

      // ---- state
      "state.ready": "就绪",
      "state.idle": "空闲",
      "state.recording": "录音中",
      "state.transcribing": "转写中",
      "state.stopped": "守护进程已停止",

      // ---- setup
      "setup.prefix": "安装 ",
      "setup.title": "还有两个组件要装",
      "setup.blurb": "这里的每一步都要你按下才会执行，并且会先把完整命令显示出来。Omarchy 有意不执行插件目录里的任何东西，所以这个页面只能来问你。",
      "setup.optional": "可选",
      "setup.copy": "复制",
      "setup.run": "运行",
      "setup.recheck": "重新检查",
      "setup.hint": "或者在终端里运行  omavoi setup  —— 步骤和顺序完全一样",

      // ---- history
      "hist.none": "还没有记录 —— 按住 %1 说话",
      "hist.yourkey": "你的按键",
      "hist.dropped": "已丢弃 —— ",
      "hist.audio": "音频",
      "hist.level": "电平",
      "hist.decode": "解码",
      "hist.model": "模型",
      "hist.language": "语言",
      "hist.mode": "模式",
      "hist.injected": "注入方式",
      "hist.said": "模型原文：  ",
      "hist.post": "后处理",
      "hist.segments": "分段置信度",
      "hist.copy": "复制",
      "hist.play": "播放",

      // ---- modes
      "modes.wontfit": "需要 %1 空闲显存",
      "modes.blocked": "未切换 —— 这个模式的模型现在装不进显存",
      "modes.newname": "新模式名称",
      "modes.here": "当前",
      "modes.fallback": "兜底",
      "modes.followwin": "模式跟随当前焦点窗口",
      "modes.everytake": "每次录音都使用 ",
      "modes.longestwins": "下面匹配最长的规则胜出；都不匹配时回落到 default。",
      "modes.matchoff": "窗口匹配已关闭，下面的列表虽已配置但不会生效。它需要为每个应用逐个调过才值得开启。",
      "modes.following": "跟随窗口",
      "modes.fixed": "固定",
      "modes.activehere": "在当前窗口生效",
      "modes.delete": "删除模式",
      "modes.opens": "触发窗口",
      "modes.notinuse": "模式固定时这里不生效",
      "modes.nothing": "无 —— 这个模式只能按名字调用",
      "modes.classph": "窗口 class，例如 thunderbird",
      "modes.add": "添加",
      "modes.matchhint": "与 Hyprland 的 class 和 title 做匹配，最长的匹配胜出。",
      "modes.s1": "1  语音",
      "modes.speechsub": "解码之前告诉模型的内容",
      "modes.language": "语言",
      "modes.langhint": "留空则每次自动检测；填 en、zh 这样的代码更快也更稳",
      "modes.decoderhint": "解码提示词",
      "modes.promptph": "会喂给模型。适合它总认错的专有名词 —— 这只是提示，不是保证；保证靠词典。",
      "modes.s2": "2  规则",
      "modes.rulessub": "确定性 · 零延迟",
      "modes.r.hallucinations": "幻觉过滤",
      "modes.r.fillers": "语气词",
      "modes.r.dictionary": "词典",
      "modes.r.names": "名称",
      "modes.r.cjk": "中英间距",
      "modes.keeppunct": "保留句末标点",
      "modes.s3": "3  LLM",
      "modes.llmsub": "可选 · 按顺序执行 · 某步失败则保留上一步的文本",
      "modes.step": "第 ",
      "modes.stepsuffix": " 步",
      "modes.remove": "移除",
      "modes.stepph": "让它改写，不要让它回答。",
      "modes.nostep": "这个模式没有 LLM 步骤，所以还没有提示词可写。在下面加一个，它的提示词就会出现在这里，可编辑，并且已经带了一份能直接用的默认内容。",
      "modes.addstep": "+ 添加一步",
      "modes.nollm": "还没有配置 LLM —— 去「模型」页",
      "modes.inject.auto": "自动",
      "modes.inject.clipboard": "剪贴板",
      "modes.langauto": "自动",
      "modes.s4": "4  注入",
      "modes.injecthint": "auto 默认用 wtype 逐字输入；遇到 XWayland 客户端和已知的 Electron 应用则改为粘贴 —— wtype 合成的键码传到那些程序里会变成数字。",

      // ---- models
      "models.speech": "语音",
      "models.speechsub": "音频 → 文本 · 只跑一个",
      "models.e.vulkan": "本地 · Vulkan",
      "models.e.vulkan.sub": "whisper.cpp · ggml 权重 · NVIDIA、AMD、Intel 都能跑",
      "models.e.vulkan.note": "约 10 MB 的软件包",
      "models.e.cuda": "本地 · CUDA",
      "models.e.cuda.sub": "faster-whisper · ct2 权重 · 仅 NVIDIA",
      "models.e.cuda.note": "约 2.2 GB 的 wheel 包",
      "models.e.api": "远程 API",
      "models.e.api.sub": "兼容 OpenAI 协议 · OpenAI、Groq、SiliconFlow，或自建服务",
      "models.e.api.note": "音频会离开本机",
      "models.llmcathint": "由模式的步骤按名字引用，不是全局切换",
      "models.now": "正在运行",
      "models.running": "运行中",
      "models.notloaded": "未加载",
      "models.cold": "未启动 · 首次使用时启动",
      "models.ready": "就绪",
      "models.nodaemon": "连不上守护进程 —— 无法得知加载了什么",
      "models.stale": "守护进程仍在跑启动时加载的那一个",
      "models.loaded": "已加载 ",
      "models.configured": "已配置 ",
      "models.restart": "重启守护进程",
      "models.list": "模型 · ",
      "models.formathint": "这个引擎使用的权重格式",
      "models.ondisk": "已在磁盘上",
      "models.downloading": "下载中…",
      "models.download": "下载",
      "models.use": "使用",
      "models.remove": "删除",
      "models.ourstore": "我们的模型目录",
      "models.outside": "在 %1 之外找到的权重会就地使用，永不删除。",
      "models.llm": "LLM",
      "models.llmsub": "文本 → 文本 · 可配多个，由模式按名字引用",
      "models.remote": "远程",
      "models.local": "本地",
      "models.nokey": "缺密钥",
      "models.usedby": "被使用于 ",
      "models.unused": "没有任何模式引用它 —— 在被引用前不占任何资源",
      "models.endpointnote": "接入点写在 [llm.<name>] 下 —— omavoi config edit。密钥绝不写进配置文件：设成环境变量，或者放进 secrets.toml。",
      "models.vram": "显存 · ",
      "models.seg.speech": "语音模型",
      "models.seg.other": "其他程序",
      "models.seg.free": "空闲",
      "models.vramsub": "全机范围的占用",
      "models.needs": "需要",
      "models.vramnote": "让两个模型都常驻是关键：每次录音都重新加载权重要花几秒，而不是几毫秒。一旦超配，被换出去的就是语音模型 —— 听写会慢十倍，而且不会有任何提示告诉你为什么。",

      // ---- dictionary
      "dict.rules": "规则",
      "dict.names": "名称",
      "dict.blurb": "听到的 → 想要的。解码提示词只是模型可以无视的建议，这里才是保证。匹配时先试最长的键，所以被它包含的更短的键永远不会触发。",
      "dict.shadowed": "永不触发 —— 被遮蔽于 ",
      "dict.remove": "移除",
      "dict.namesblurb": "只写正确的写法。名称会被喂进解码提示词，让模型倾向于产出它们，之后再按读音匹配，把同音的写法收回来。匹配默认关闭，直到你看过一次试运行 —— 这是这里唯一可能把原本正确的文字改坏的功能。",
      "dict.matching": "匹配中",
      "dict.seedonly": "仅提示",
      "dict.dryrun": "试运行",
      "dict.enable": "开启匹配",
      "dict.prompt": "提示词： ",
      "dict.none": "（无）",
      "dict.addrule": "用  omavoi dict add <听到> <想要>  添加一条",
      "dict.addnames": "用  omavoi names add <名字> <名字> …  一次加多个",

      // ---- settings
      "set.ptt": "按住说话",
      "set.toggle": "按一下切换",
      "set.dwell.always": "总是",
      "set.dwell.changed": "有改动时",
      "set.dwell.never": "从不",
      "set.hotkey": "快捷键",
      "set.key": "按键",
      "set.behaviour": "行为",
      "set.hotkeynote": "直接从 evdev 读取，位于 xkb 之下，所以即使你的键盘布局把它重映射了，这个键的物理位置也不变。换成在 Hyprland 里绑一个修饰键是不行的：按下修饰键会改变 modmask，松开绑定会立刻触发，录出一条 0.0 秒的记录。",
      "set.audio": "音频",
      "set.preroll": "前置缓冲",
      "set.prerollwhy": "保留按键按下之前的一段音频。调小了，PipeWire 打开音频流的这段时间里第一个音节就会开始丢。",
      "set.tail": "尾部延时",
      "set.warnbelow": "低于则警告",
      "set.maxtake": "单次上限",
      "set.hud": "HUD",
      "set.keepup": "结果保持显示",
      "set.hudnote": "默认是 \"changed\"：每次都停留一下，等你连着说两句话就变成了干扰；但一次你根本没看见的静默改写更糟。",
      "set.notifications": "通知",
      "set.on": "开",
      "set.off": "关",
      "set.history": "历史",
      "set.keepaudio": "保留音频",
      "set.takes": " 条",
      "set.historynote": "存下的音频是「换个模型重跑一次」和名称试运行的前提。设成 0，这两个功能也一起没了。",
      "set.privacy": "你的声音去了哪里",
      "set.neverleaves": "音频永不离开本机",
      "set.privacynote": "所有模式的语音识别都跑在本地 GPU 上。但如果某个模式的 LLM 步骤用的是远程模型，转写出来的文本确实会发出去 —— 「模式」页里可以看到哪些模式有 LLM 步骤。",
      "set.editconfig": "编辑配置",
      "set.restart": "重启守护进程",
      "set.configpath": "这里的一切都在  ~/.config/omavoi/config.toml"
    },
    th: {
      // ---- nav
      "nav.history": "ประวัติ",
      "nav.modes": "โหมด",
      "nav.models": "โมเดล",
      "nav.dictionary": "พจนานุกรม",
      "nav.settings": "ตั้งค่า",
      "lang.label": "ภาษา",

      // ---- state
      "state.ready": "พร้อม",
      "state.idle": "ว่าง",
      "state.recording": "กำลังอัดเสียง",
      "state.transcribing": "กำลังถอดเสียง",
      "state.stopped": "เดมอนหยุดทำงาน",

      // ---- setup
      "setup.prefix": "ติดตั้ง ",
      "setup.title": "เหลืออีกสองส่วนที่ต้องติดตั้ง",
      "setup.blurb": "ไม่มีอะไรทำงานจนกว่าคุณจะกด และทุกขั้นจะแสดงคำสั่งจริงให้ดูก่อน Omarchy ตั้งใจไม่รันสิ่งใด จากในโฟลเดอร์ปลั๊กอิน หน้านี้จึงต้องถามคุณแทน",
      "setup.optional": "ไม่บังคับ",
      "setup.copy": "คัดลอก",
      "setup.run": "รัน",
      "setup.recheck": "ตรวจอีกครั้ง",
      "setup.hint": "หรือรัน  omavoi setup  ในเทอร์มินัล — ขั้นตอนและลำดับเดียวกัน",

      // ---- history
      "hist.none": "ยังไม่มีรายการ — กด %1 ค้างไว้แล้วพูด",
      "hist.yourkey": "ปุ่มของคุณ",
      "hist.dropped": "ถูกทิ้ง — ",
      "hist.audio": "เสียง",
      "hist.level": "ระดับ",
      "hist.decode": "ถอดรหัส",
      "hist.model": "โมเดล",
      "hist.language": "ภาษา",
      "hist.mode": "โหมด",
      "hist.injected": "วิธีป้อน",
      "hist.said": "โมเดลได้ยินว่า:  ",
      "hist.post": "การประมวลผลภายหลัง",
      "hist.segments": "ความมั่นใจต่อช่วง",
      "hist.copy": "คัดลอก",
      "hist.play": "เล่น",

      // ---- modes
      "modes.wontfit": "ต้องมี %1 ว่าง",
      "modes.blocked": "ไม่ได้สลับ — โมเดลของโหมดนี้ใส่ใน VRAM ตอนนี้ไม่พอ",
      "modes.newname": "ชื่อโหมดใหม่",
      "modes.here": "ที่นี่",
      "modes.fallback": "สำรอง",
      "modes.followwin": "โหมดจะตามหน้าต่างที่โฟกัส",
      "modes.everytake": "ทุกครั้งจะใช้ ",
      "modes.longestwins": "กฎที่ตรงยาวที่สุดด้านล่างชนะ ถ้าไม่ตรงเลยจะกลับไปใช้ default",
      "modes.matchoff": "การจับคู่หน้าต่างปิดอยู่ รายการด้านล่างจึงถูกตั้งไว้แต่ไม่ทำงาน ต้องปรับทีละแอปก่อนจะคุ้มค่าที่จะเปิด",
      "modes.following": "ตามหน้าต่าง",
      "modes.fixed": "คงที่",
      "modes.activehere": "ทำงานในหน้าต่างนี้",
      "modes.delete": "ลบโหมด",
      "modes.opens": "เปิดเมื่อ",
      "modes.notinuse": "ไม่ถูกใช้ขณะโหมดถูกตั้งคงที่",
      "modes.nothing": "ไม่มี — โหมดนี้เรียกได้ด้วยชื่อเท่านั้น",
      "modes.classph": "คลาสหน้าต่าง เช่น thunderbird",
      "modes.add": "เพิ่ม",
      "modes.matchhint": "เทียบกับ class และ title ของ Hyprland กฎที่ตรงยาวที่สุดชนะ",
      "modes.s1": "1  เสียงพูด",
      "modes.speechsub": "สิ่งที่บอกโมเดลก่อนเริ่มถอดเสียง",
      "modes.language": "ภาษา",
      "modes.langhint": "ปล่อยว่างจะตรวจทุกครั้ง ใส่รหัสอย่าง en หรือ zh จะเร็วและนิ่งกว่า",
      "modes.decoderhint": "คำใบ้ให้ตัวถอดเสียง",
      "modes.promptph": "ถูกป้อนเข้าโมเดล เหมาะกับศัพท์เฉพาะที่มันเพี้ยนบ่อย — เป็นคำใบ้ ไม่ใช่การรับประกัน ตัวที่รับประกันคือพจนานุกรม",
      "modes.s2": "2  กฎ",
      "modes.rulessub": "แน่นอน · ไม่มีดีเลย์",
      "modes.r.hallucinations": "การหลอน",
      "modes.r.fillers": "คำเติม",
      "modes.r.dictionary": "พจนานุกรม",
      "modes.r.names": "ชื่อเฉพาะ",
      "modes.r.cjk": "ระยะห่าง CJK",
      "modes.keeppunct": "คงเครื่องหมายท้ายประโยค",
      "modes.s3": "3  LLM",
      "modes.llmsub": "ไม่บังคับ · ทำตามลำดับ · ถ้าล้มเหลวจะคงข้อความเดิมไว้",
      "modes.step": "ขั้น ",
      "modes.stepsuffix": "",
      "modes.remove": "เอาออก",
      "modes.stepph": "สั่งให้แก้ข้อความ ไม่ใช่ให้ตอบ",
      "modes.nostep": "โหมดนี้ไม่มีขั้น LLM จึงยังไม่มีพรอมป์ตให้เขียน เพิ่มด้านล่างแล้วพรอมป์ตจะปรากฏที่นี่ แก้ไขได้ และมีค่าเริ่มต้นที่ใช้งานได้อยู่แล้ว",
      "modes.addstep": "+ เพิ่มขั้น",
      "modes.nollm": "ยังไม่ได้ตั้งค่า LLM — ดูที่แท็บโมเดล",
      "modes.inject.auto": "อัตโนมัติ",
      "modes.inject.clipboard": "คลิปบอร์ด",
      "modes.langauto": "อัตโนมัติ",
      "modes.s4": "4  การป้อนข้อความ",
      "modes.injecthint": "auto จะพิมพ์ด้วย wtype ยกเว้นไคลเอนต์ XWayland และแอป Electron ที่รู้จัก ซึ่งจะใช้การวางแทน — คีย์โค้ดสังเคราะห์ของ wtype ไปถึงแอปพวกนั้นเป็นตัวเลข",

      // ---- models
      "models.speech": "เสียงพูด",
      "models.speechsub": "เสียง → ข้อความ · ทำงานตัวเดียว",
      "models.e.vulkan": "ในเครื่อง · Vulkan",
      "models.e.vulkan.sub": "whisper.cpp · น้ำหนัก ggml · ใช้ได้ทั้ง NVIDIA, AMD และ Intel",
      "models.e.vulkan.note": "แพ็กเกจราว 10 MB",
      "models.e.cuda": "ในเครื่อง · CUDA",
      "models.e.cuda.sub": "faster-whisper · น้ำหนัก ct2 · NVIDIA เท่านั้น",
      "models.e.cuda.note": "wheel ราว 2.2 GB",
      "models.e.api": "API ระยะไกล",
      "models.e.api.sub": "รองรับรูปแบบ OpenAI · OpenAI, Groq, SiliconFlow หรือเซิร์ฟเวอร์ในเครื่อง",
      "models.e.api.note": "เสียงจะออกจากเครื่องนี้",
      "models.llmcathint": "โหมดเรียกใช้ตามชื่อในขั้นของมัน ไม่ใช่การสลับทั้งระบบ",
      "models.now": "ที่กำลังทำงาน",
      "models.running": "กำลังทำงาน",
      "models.notloaded": "ยังไม่ได้โหลด",
      "models.cold": "ยังไม่เริ่ม · จะเริ่มเมื่อใช้ครั้งแรก",
      "models.ready": "พร้อม",
      "models.nodaemon": "ติดต่อเดมอนไม่ได้ — ไม่ทราบว่าโหลดอะไรไว้",
      "models.stale": "เดมอนยังรันตัวที่โหลดไว้ตอนเริ่มอยู่",
      "models.loaded": "โหลดแล้ว ",
      "models.configured": "ตั้งค่าไว้ ",
      "models.restart": "รีสตาร์ตเดมอน",
      "models.list": "โมเดล · ",
      "models.formathint": "รูปแบบน้ำหนักที่เอนจินนี้ใช้",
      "models.ondisk": "มีอยู่ในดิสก์แล้ว",
      "models.downloading": "กำลังดาวน์โหลด…",
      "models.download": "ดาวน์โหลด",
      "models.use": "ใช้",
      "models.remove": "ลบ",
      "models.ourstore": "คลังของเรา",
      "models.outside": "น้ำหนักที่พบนอก %1 จะถูกใช้ตามที่อยู่เดิมและไม่ถูกลบ",
      "models.llm": "LLM",
      "models.llmsub": "ข้อความ → ข้อความ · มีได้หลายตัว โหมดเรียกตามชื่อ",
      "models.remote": "ระยะไกล",
      "models.local": "ในเครื่อง",
      "models.nokey": "ไม่มีคีย์",
      "models.usedby": "ใช้โดย ",
      "models.unused": "ยังไม่มีโหมดใดเรียกใช้ — ไม่กินทรัพยากรจนกว่าจะมี",
      "models.endpointnote": "ปลายทางอยู่ใต้ [llm.<name>] — omavoi config edit คีย์ไม่เคยอยู่ในไฟล์ตั้งค่า: ตั้งเป็นตัวแปรสภาพแวดล้อม หรือใส่ใน secrets.toml",
      "models.vram": "VRAM · ",
      "models.seg.speech": "โมเดลเสียงพูด",
      "models.seg.other": "โปรแกรมอื่น",
      "models.seg.free": "ว่าง",
      "models.vramsub": "ที่ใช้อยู่ทั้งเครื่อง",
      "models.needs": "ต้องใช้",
      "models.vramnote": "การให้ทั้งสองตัวค้างในหน่วยความจำคือหัวใจ: สายที่โหลดน้ำหนักใหม่ทุกครั้งเสียเวลาเป็นวินาที ไม่ใช่มิลลิวินาที ถ้าจัดเกินโควตา ตัวที่ถูกไล่ออกคือโมเดลเสียงพูด — การพิมพ์ด้วยเสียงจะช้าลงสิบเท่าโดยไม่มีอะไรบอกสาเหตุ",

      // ---- dictionary
      "dict.rules": "กฎ",
      "dict.names": "ชื่อเฉพาะ",
      "dict.blurb": "ที่ได้ยิน → ที่ต้องการ พรอมป์ตของตัวถอดเสียงเป็นเพียงคำใบ้ที่โมเดลอาจเมิน ส่วนนี้คือตัวรับประกัน คีย์ที่ยาวที่สุดถูกลองก่อน คีย์สั้นที่อยู่ข้างในจึงไม่มีวันทำงาน",
      "dict.shadowed": "ไม่เคยทำงาน — ถูกกลบโดย ",
      "dict.remove": "เอาออก",
      "dict.namesblurb": "เขียนเฉพาะรูปที่ถูกต้อง ชื่อจะถูกป้อนเข้าพรอมป์ตของตัวถอดเสียงเพื่อให้โมเดลสร้างมันออกมา แล้วจับคู่ด้วยเสียงภายหลังเพื่อรวมคำพ้องเสียงกลับ การจับคู่จะปิดไว้จนคุณได้ดูผลทดลองก่อน — นี่เป็นสิ่งเดียวในหน้านี้ที่ทำให้ข้อความที่ถูกอยู่แล้วเสียได้",
      "dict.matching": "จับคู่อยู่",
      "dict.seedonly": "ป้อนพรอมป์ตเท่านั้น",
      "dict.dryrun": "ทดลองรัน",
      "dict.enable": "เปิดการจับคู่",
      "dict.prompt": "พรอมป์ต: ",
      "dict.none": "(ไม่มี)",
      "dict.addrule": "เพิ่มด้วย  omavoi dict add <ที่ได้ยิน> <ที่ต้องการ>",
      "dict.addnames": "เพิ่มหลายรายการพร้อมกันด้วย  omavoi names add <ชื่อ> <ชื่อ> …",

      // ---- settings
      "set.ptt": "กดค้างเพื่อพูด",
      "set.toggle": "สลับเปิด/ปิด",
      "set.dwell.always": "เสมอ",
      "set.dwell.changed": "เมื่อมีการแก้",
      "set.dwell.never": "ไม่เลย",
      "set.hotkey": "ปุ่มลัด",
      "set.key": "ปุ่ม",
      "set.behaviour": "พฤติกรรม",
      "set.hotkeynote": "อ่านจาก evdev ซึ่งอยู่ต่ำกว่า xkb ปุ่มจึงอยู่ตำแหน่งจริงเสมอแม้เลย์เอาต์จะรีแมป จะผูกปุ่มมอดิฟายเออร์ใน Hyprland แทนไม่ได้: การกดมันเปลี่ยน modmask ทำให้ทริกเกอร์ปล่อยปุ่มทำงานทันทีและได้รายการยาว 0.0 วินาที",
      "set.audio": "เสียง",
      "set.preroll": "บัฟเฟอร์นำหน้า",
      "set.prerollwhy": "เสียงที่เก็บไว้ก่อนกดปุ่ม ถ้าลดลง พยางค์แรกจะเริ่มหายไปช่วงที่ PipeWire เปิดสตรีม",
      "set.tail": "ส่วนท้าย",
      "set.warnbelow": "เตือนเมื่อต่ำกว่า",
      "set.maxtake": "ความยาวสูงสุด",
      "set.hud": "HUD",
      "set.keepup": "คงผลลัพธ์ไว้บนจอ",
      "set.hudnote": "ค่าเริ่มต้นคือ \"changed\": การค้างจอทุกครั้งจะกลายเป็นสิ่งรบกวนทันทีที่คุณพูดสองประโยคติดกัน แต่การแก้ไขเงียบ ๆ ที่คุณไม่เคยเห็นแย่กว่า",
      "set.notifications": "การแจ้งเตือน",
      "set.on": "เปิด",
      "set.off": "ปิด",
      "set.history": "ประวัติ",
      "set.keepaudio": "เก็บเสียงไว้",
      "set.takes": " รายการ",
      "set.historynote": "เสียงที่เก็บไว้คือสิ่งที่ทำให้รันรายการเดิมด้วยโมเดลอื่น และการทดลองรันชื่อ เป็นไปได้ ตั้งเป็น 0 แล้วสองอย่างนั้นก็หายไปด้วย",
      "set.privacy": "เสียงของคุณไปที่ไหน",
      "set.neverleaves": "เสียงไม่เคยออกจากเครื่องนี้",
      "set.privacynote": "การถอดเสียงทำงานบน GPU ในเครื่องทุกโหมด แต่โหมดที่ขั้น LLM ใช้โมเดลระยะไกล จะส่งข้อความที่ถอดได้ออกไปจริง — แท็บโหมดแสดงว่าโหมดใดมีขั้นนั้นบ้าง",
      "set.editconfig": "แก้ไฟล์ตั้งค่า",
      "set.restart": "รีสตาร์ตเดมอน",
      "set.configpath": "ทุกอย่างในหน้านี้อยู่ที่  ~/.config/omavoi/config.toml"
    },
    de: {
      // ---- nav
      "nav.history": "Verlauf",
      "nav.modes": "Modi",
      "nav.models": "Modelle",
      "nav.dictionary": "Wörterbuch",
      "nav.settings": "Einstellungen",
      "lang.label": "Sprache",

      // ---- state
      "state.ready": "Bereit",
      "state.idle": "bereit",
      "state.recording": "Aufnahme",
      "state.transcribing": "Transkription",
      "state.stopped": "Dienst gestoppt",

      // ---- setup
      "setup.prefix": "Einrichtung ",
      "setup.title": "Noch zwei Teile zu installieren",
      "setup.blurb": "Hier läuft nichts, bis du es anstößt, und jeder Schritt zeigt vorher den genauen Befehl. Omarchy führt absichtlich nichts aus einem Plugin-Ordner aus, deshalb fragt dieser Bildschirm.",
      "setup.optional": "optional",
      "setup.copy": "Kopieren",
      "setup.run": "Ausführen",
      "setup.recheck": "Neu prüfen",
      "setup.hint": "oder  omavoi setup  im Terminal ausführen — gleiche Schritte, gleiche Reihenfolge",

      // ---- history
      "hist.none": "noch keine Aufnahmen — %1 halten und sprechen",
      "hist.yourkey": "deine Taste",
      "hist.dropped": "verworfen — ",
      "hist.audio": "Audio",
      "hist.level": "Pegel",
      "hist.decode": "Dekodierung",
      "hist.model": "Modell",
      "hist.language": "Sprache",
      "hist.mode": "Modus",
      "hist.injected": "eingefügt per",
      "hist.said": "Modell sagte:  ",
      "hist.post": "NACHBEARBEITUNG",
      "hist.segments": "SEGMENT-KONFIDENZ",
      "hist.copy": "Kopieren",
      "hist.play": "Abspielen",

      // ---- modes
      "modes.wontfit": "braucht %1 frei",
      "modes.blocked": "nicht gewechselt — das Modell dieses Modus passt gerade nicht in den VRAM",
      "modes.newname": "Name des neuen Modus",
      "modes.here": "hier",
      "modes.fallback": "Rückfall",
      "modes.followwin": "Der Modus folgt dem fokussierten Fenster",
      "modes.everytake": "Jede Aufnahme nutzt ",
      "modes.longestwins": "Die längste Übereinstimmung unten gewinnt; passt nichts, greift default.",
      "modes.matchoff": "Fensterabgleich ist aus, die Listen unten sind also konfiguriert, aber wirkungslos. Er will pro Anwendung eingestellt werden, bevor er sich lohnt.",
      "modes.following": "folgt dem Fenster",
      "modes.fixed": "fest",
      "modes.activehere": "in diesem Fenster aktiv",
      "modes.delete": "Modus löschen",
      "modes.opens": "ÖFFNET BEI",
      "modes.notinuse": "nicht in Gebrauch, solange der Modus fest ist",
      "modes.nothing": "nichts — dieser Modus wird nur über seinen Namen erreicht",
      "modes.classph": "Fensterklasse, z. B. thunderbird",
      "modes.add": "Hinzufügen",
      "modes.matchhint": "Abgeglichen mit Klasse und Titel aus Hyprland. Die längste Übereinstimmung gewinnt.",
      "modes.s1": "1  SPRACHE",
      "modes.speechsub": "was das Modell erfährt, bevor es dekodiert",
      "modes.language": "Sprache",
      "modes.langhint": "leer erkennt sie pro Aufnahme; ein Code wie en oder zh ist schneller und stabiler",
      "modes.decoderhint": "Decoder-Hinweis",
      "modes.promptph": "Wird dem Modell mitgegeben. Gut für Fachwörter, die es immer verstümmelt — ein Hinweis, keine Garantie; die Garantie ist das Wörterbuch.",
      "modes.s2": "2  REGELN",
      "modes.rulessub": "deterministisch · ohne Latenz",
      "modes.r.hallucinations": "Halluzinationen",
      "modes.r.fillers": "Füllwörter",
      "modes.r.dictionary": "Wörterbuch",
      "modes.r.names": "Namen",
      "modes.r.cjk": "CJK-Abstände",
      "modes.keeppunct": "Satzzeichen am Ende behalten",
      "modes.s3": "3  LLM",
      "modes.llmsub": "optional · läuft in Reihenfolge · ein Fehlschlag behält den erhaltenen Text",
      "modes.step": "Schritt ",
      "modes.stepsuffix": "",
      "modes.remove": "Entfernen",
      "modes.stepph": "Sag ihm, es soll bearbeiten, nicht antworten.",
      "modes.nostep": "Dieser Modus hat keinen LLM-Durchlauf, also gibt es noch keinen Prompt zu schreiben. Füge unten einen hinzu, dann erscheint sein Prompt hier, bearbeitbar und mit brauchbarer Vorbelegung.",
      "modes.addstep": "+ Schritt hinzufügen",
      "modes.nollm": "kein LLM konfiguriert — siehe Tab Modelle",
      "modes.inject.auto": "auto",
      "modes.inject.clipboard": "Zwischenablage",
      "modes.langauto": "auto",
      "modes.s4": "4  EINFÜGEN",
      "modes.injecthint": "auto tippt mit wtype, außer in XWayland-Clients und bekannten Electron-Apps, wo es stattdessen einfügt — dort kommen die synthetischen Keycodes von wtype als Ziffern an.",

      // ---- models
      "models.speech": "SPRACHE",
      "models.speechsub": "Audio → Text · eines läuft",
      "models.e.vulkan": "Lokal · Vulkan",
      "models.e.vulkan.sub": "whisper.cpp · ggml-Gewichte · NVIDIA, AMD und Intel gleichermaßen",
      "models.e.vulkan.note": "~10 MB Pakete",
      "models.e.cuda": "Lokal · CUDA",
      "models.e.cuda.sub": "faster-whisper · ct2-Gewichte · nur NVIDIA",
      "models.e.cuda.note": "~2,2 GB Wheels",
      "models.e.api": "Remote-API",
      "models.e.api.sub": "OpenAI-kompatibel · OpenAI, Groq, SiliconFlow, ein lokaler Server",
      "models.e.api.note": "Audio verlässt diesen Rechner",
      "models.llmcathint": "von einem Modus-Schritt genannt, nicht global umgeschaltet",
      "models.now": "LÄUFT JETZT",
      "models.running": "läuft",
      "models.notloaded": "nicht geladen",
      "models.cold": "kalt · startet beim ersten Gebrauch",
      "models.ready": "bereit",
      "models.nodaemon": "Dienst nicht erreichbar — was geladen ist, ist unbekannt",
      "models.stale": "Der Dienst läuft noch mit dem, womit er gestartet ist",
      "models.loaded": "geladen ",
      "models.configured": "konfiguriert ",
      "models.restart": "Dienst neu starten",
      "models.list": "MODELLE · ",
      "models.formathint": "das Format, das diese Engine ausführt",
      "models.ondisk": "schon auf der Platte",
      "models.downloading": "wird geladen…",
      "models.download": "Herunterladen",
      "models.use": "Verwenden",
      "models.remove": "Entfernen",
      "models.ourstore": "unserem Speicher",
      "models.outside": "Gewichte außerhalb von %1 werden dort genutzt, wo sie liegen, und nie gelöscht.",
      "models.llm": "LLM",
      "models.llmsub": "Text → Text · beliebig viele, von Modi namentlich aufgerufen",
      "models.remote": "remote",
      "models.local": "lokal",
      "models.nokey": "kein Key",
      "models.usedby": "genutzt von ",
      "models.unused": "von keinem Modus genannt — kostet nichts, bis einer es tut",
      "models.endpointnote": "Endpunkte stehen unter [llm.<name>] — omavoi config edit. Ein Key kommt nie in die Konfiguration: setze seine Umgebungsvariable oder lege ihn in secrets.toml.",
      "models.vram": "VRAM · ",
      "models.seg.speech": "Sprachmodell",
      "models.seg.other": "andere Programme",
      "models.seg.free": "frei",
      "models.vramsub": "im gesamten Rechner belegt",
      "models.needs": "braucht",
      "models.vramnote": "Beide dauerhaft im Speicher zu halten ist der Punkt: eine Kette, die Gewichte pro Aufnahme lädt, kostet Sekunden statt Millisekunden. Bei Überbuchung wird das Sprachmodell verdrängt — das Diktat wird zehnmal langsamer, ohne dass etwas sagt warum.",

      // ---- dictionary
      "dict.rules": "Regeln",
      "dict.names": "Namen",
      "dict.blurb": "gehört → gemeint. Ein Decoder-Prompt ist ein Hinweis, den das Modell ignorieren darf; hier steht die Garantie. Der längste Schlüssel wird zuerst probiert, ein darin enthaltener kürzerer greift also nie.",
      "dict.shadowed": "greift nie — verdeckt von ",
      "dict.remove": "Entfernen",
      "dict.namesblurb": "Schreibe nur die richtige Form. Namen gehen in den Decoder-Prompt, damit das Modell sie erzeugt, und werden danach klanglich abgeglichen, damit Homophone zurückfallen. Der Abgleich bleibt aus, bis ein Probelauf angesehen wurde — er ist das Einzige hier, das schon richtigen Text beschädigen kann.",
      "dict.matching": "Abgleich",
      "dict.seedonly": "nur Prompt",
      "dict.dryrun": "Probelauf",
      "dict.enable": "Abgleich aktivieren",
      "dict.prompt": "Prompt: ",
      "dict.none": "(keiner)",
      "dict.addrule": "Eine anlegen mit  omavoi dict add <gehört> <gemeint>",
      "dict.addnames": "Mehrere auf einmal mit  omavoi names add <Name> <Name> …",

      // ---- settings
      "set.ptt": "Halten zum Sprechen",
      "set.toggle": "Umschalten",
      "set.dwell.always": "immer",
      "set.dwell.changed": "bei Änderung",
      "set.dwell.never": "nie",
      "set.hotkey": "TASTENKÜRZEL",
      "set.key": "Taste",
      "set.behaviour": "Verhalten",
      "set.hotkeynote": "Direkt von evdev gelesen, unterhalb von xkb, damit die Taste physisch dort bleibt, wo sie ist, auch wenn dein Layout sie umbelegt. Ein Modifier lässt sich in Hyprland nicht binden: ihn zu drücken ändert die Modmask, was die Release-Bindung sofort auslöst und eine Aufnahme von 0,0 s ergibt.",
      "set.audio": "AUDIO",
      "set.preroll": "Vorlauf",
      "set.prerollwhy": "Audio von vor dem Tastendruck. Verkleinere es, und die erste Silbe fehlt zunehmend, während PipeWire den Stream öffnet.",
      "set.tail": "Nachlauf",
      "set.warnbelow": "warnen unter",
      "set.maxtake": "max. Aufnahme",
      "set.hud": "HUD",
      "set.keepup": "Ergebnis stehen lassen",
      "set.hudnote": "„changed“ ist die Vorgabe: eine Standzeit, die du immer bezahlst, wird zum Rauschen, sobald du zwei Sätze hintereinander diktierst — aber eine stille Korrektur, die du nie gesehen hast, ist schlimmer.",
      "set.notifications": "Benachrichtigungen",
      "set.on": "ein",
      "set.off": "aus",
      "set.history": "VERLAUF",
      "set.keepaudio": "Audio behalten für",
      "set.takes": " Aufnahmen",
      "set.historynote": "Gespeichertes Audio macht es möglich, eine Aufnahme mit einem anderen Modell zu wiederholen und den Namens-Probelauf zu fahren. Auf 0 gesetzt, verschwindet beides mit.",
      "set.privacy": "WOHIN DEINE STIMME GEHT",
      "set.neverleaves": "Audio verlässt diesen Rechner nie",
      "set.privacynote": "Die Spracherkennung läuft in jedem Modus auf der lokalen GPU. Ein Modus, dessen LLM-Schritt ein Remote-Modell ist, schickt den transkribierten Text hinaus — der Tab Modi zeigt, welche überhaupt einen Schritt haben.",
      "set.editconfig": "Konfiguration bearbeiten",
      "set.restart": "Dienst neu starten",
      "set.configpath": "alles hier ist  ~/.config/omavoi/config.toml"
    },
    fr: {
      // ---- nav
      "nav.history": "Historique",
      "nav.modes": "Modes",
      "nav.models": "Modèles",
      "nav.dictionary": "Dictionnaire",
      "nav.settings": "Réglages",
      "lang.label": "Langue",

      // ---- state
      "state.ready": "Prêt",
      "state.idle": "au repos",
      "state.recording": "enregistrement",
      "state.transcribing": "transcription",
      "state.stopped": "démon arrêté",

      // ---- setup
      "setup.prefix": "installation ",
      "setup.title": "Encore deux éléments à installer",
      "setup.blurb": "Rien ne s'exécute ici avant que tu ne l'actionnes, et chaque étape montre d'abord la commande exacte. Omarchy n'exécute délibérément rien depuis un dossier de plugin, donc cet écran demande.",
      "setup.optional": "facultatif",
      "setup.copy": "Copier",
      "setup.run": "Exécuter",
      "setup.recheck": "Revérifier",
      "setup.hint": "ou lance  omavoi setup  dans un terminal — mêmes étapes, même ordre",

      // ---- history
      "hist.none": "aucune prise pour l'instant — maintiens %1 et parle",
      "hist.yourkey": "ta touche",
      "hist.dropped": "rejetée — ",
      "hist.audio": "audio",
      "hist.level": "niveau",
      "hist.decode": "décodage",
      "hist.model": "modèle",
      "hist.language": "langue",
      "hist.mode": "mode",
      "hist.injected": "inséré via",
      "hist.said": "le modèle a dit :  ",
      "hist.post": "POST-TRAITEMENT",
      "hist.segments": "CONFIANCE PAR SEGMENT",
      "hist.copy": "Copier",
      "hist.play": "Écouter",

      // ---- modes
      "modes.wontfit": "demande %1 de libre",
      "modes.blocked": "non basculé — le modèle de ce mode ne tient pas dans la VRAM actuellement",
      "modes.newname": "nom du nouveau mode",
      "modes.here": "ici",
      "modes.fallback": "par défaut",
      "modes.followwin": "Le mode suit la fenêtre active",
      "modes.everytake": "Chaque prise utilise ",
      "modes.longestwins": "La correspondance la plus longue ci-dessous gagne ; sans correspondance, retour à default.",
      "modes.matchoff": "La correspondance de fenêtre est désactivée : les listes ci-dessous sont configurées mais inertes. Il faut l'ajuster application par application avant qu'elle ne soit rentable.",
      "modes.following": "suit la fenêtre",
      "modes.fixed": "fixe",
      "modes.activehere": "actif dans cette fenêtre",
      "modes.delete": "Supprimer le mode",
      "modes.opens": "S'OUVRE SUR",
      "modes.notinuse": "inutilisé tant que le mode est fixe",
      "modes.nothing": "rien — ce mode ne s'atteint que par son nom",
      "modes.classph": "classe de fenêtre, p. ex. thunderbird",
      "modes.add": "Ajouter",
      "modes.matchhint": "Comparé à la classe et au titre Hyprland. La correspondance la plus longue gagne.",
      "modes.s1": "1  PAROLE",
      "modes.speechsub": "ce que le modèle apprend avant de décoder",
      "modes.language": "langue",
      "modes.langhint": "vide la détecte à chaque prise ; un code comme en ou zh est plus rapide et plus stable",
      "modes.decoderhint": "indice au décodeur",
      "modes.promptph": "Transmis au modèle. Utile pour le jargon qu'il déforme toujours — un indice, pas une garantie ; la garantie, c'est le dictionnaire.",
      "modes.s2": "2  RÈGLES",
      "modes.rulessub": "déterministe · sans latence",
      "modes.r.hallucinations": "hallucinations",
      "modes.r.fillers": "mots de remplissage",
      "modes.r.dictionary": "dictionnaire",
      "modes.r.names": "noms",
      "modes.r.cjk": "espacement CJK",
      "modes.keeppunct": "garder la ponctuation finale",
      "modes.s3": "3  LLM",
      "modes.llmsub": "facultatif · exécuté dans l'ordre · un échec conserve le texte reçu",
      "modes.step": "étape ",
      "modes.stepsuffix": "",
      "modes.remove": "Retirer",
      "modes.stepph": "Dis-lui de corriger, pas de répondre.",
      "modes.nostep": "Ce mode n'a aucune passe LLM, il n'y a donc pas encore de prompt à écrire. Ajoutes-en une ci-dessous et son prompt apparaîtra ici, modifiable, avec une valeur par défaut utilisable.",
      "modes.addstep": "+ ajouter une étape",
      "modes.nollm": "aucun LLM configuré — voir l'onglet Modèles",
      "modes.inject.auto": "auto",
      "modes.inject.clipboard": "presse-papiers",
      "modes.langauto": "auto",
      "modes.s4": "4  INSERTION",
      "modes.injecthint": "auto tape avec wtype, sauf dans les clients XWayland et les applications Electron connues, où il colle à la place — les keycodes synthétiques de wtype y arrivent sous forme de chiffres.",

      // ---- models
      "models.speech": "PAROLE",
      "models.speechsub": "audio → texte · un seul tourne",
      "models.e.vulkan": "Local · Vulkan",
      "models.e.vulkan.sub": "whisper.cpp · poids ggml · NVIDIA, AMD et Intel indifféremment",
      "models.e.vulkan.note": "~10 Mo de paquets",
      "models.e.cuda": "Local · CUDA",
      "models.e.cuda.sub": "faster-whisper · poids ct2 · NVIDIA uniquement",
      "models.e.cuda.note": "~2,2 Go de wheels",
      "models.e.api": "API distante",
      "models.e.api.sub": "compatible OpenAI · OpenAI, Groq, SiliconFlow, un serveur local",
      "models.e.api.note": "l'audio quitte cette machine",
      "models.llmcathint": "nommé par une étape de mode, pas un basculement global",
      "models.now": "EN COURS",
      "models.running": "en cours",
      "models.notloaded": "non chargé",
      "models.cold": "à froid · démarre à la première utilisation",
      "models.ready": "prêt",
      "models.nodaemon": "démon injoignable — impossible de savoir ce qui est chargé",
      "models.stale": "Le démon tourne toujours avec ce qu'il a chargé au démarrage",
      "models.loaded": "chargé ",
      "models.configured": "configuré ",
      "models.restart": "Redémarrer le démon",
      "models.list": "MODÈLES · ",
      "models.formathint": "le format que ce moteur exécute",
      "models.ondisk": "déjà sur le disque",
      "models.downloading": "téléchargement…",
      "models.download": "Télécharger",
      "models.use": "Utiliser",
      "models.remove": "Supprimer",
      "models.ourstore": "notre dépôt",
      "models.outside": "Les poids trouvés hors de %1 sont utilisés là où ils sont et jamais supprimés.",
      "models.llm": "LLM",
      "models.llmsub": "texte → texte · autant qu'on veut, appelés par leur nom depuis les modes",
      "models.remote": "distant",
      "models.local": "local",
      "models.nokey": "pas de clé",
      "models.usedby": "utilisé par ",
      "models.unused": "nommé par aucun mode — ne coûte rien tant que ce n'est pas le cas",
      "models.endpointnote": "Les points d'accès vivent sous [llm.<name>] — omavoi config edit. Une clé ne va jamais dans la configuration : définis sa variable d'environnement, ou mets-la dans secrets.toml.",
      "models.vram": "VRAM · ",
      "models.seg.speech": "modèle de parole",
      "models.seg.other": "autres programmes",
      "models.seg.free": "libre",
      "models.vramsub": "utilisée sur toute la machine",
      "models.needs": "requiert",
      "models.vramnote": "Garder les deux en mémoire est tout l'intérêt : une chaîne qui charge les poids à chaque prise coûte des secondes, pas des millisecondes. En surengagement, c'est le modèle de parole qui est évincé — la dictée devient dix fois plus lente sans que rien n'en dise la raison.",

      // ---- dictionary
      "dict.rules": "règles",
      "dict.names": "noms",
      "dict.blurb": "entendu → voulu. Un prompt de décodeur est un indice que le modèle peut ignorer ; ici, c'est la garantie. La clé la plus longue est essayée d'abord, donc une plus courte qu'elle contient ne se déclenche jamais.",
      "dict.shadowed": "ne se déclenche jamais — masquée par ",
      "dict.remove": "Retirer",
      "dict.namesblurb": "N'écris que la forme correcte. Les noms sont injectés dans le prompt du décodeur pour que le modèle les produise, puis appariés par le son pour que les homophones se rabattent dessus. L'appariement reste désactivé jusqu'à ce qu'un essai à blanc ait été examiné — c'est la seule chose ici qui puisse abîmer un texte déjà correct.",
      "dict.matching": "appariement",
      "dict.seedonly": "prompt seulement",
      "dict.dryrun": "Essai à blanc",
      "dict.enable": "Activer l'appariement",
      "dict.prompt": "prompt : ",
      "dict.none": "(aucun)",
      "dict.addrule": "Ajoutes-en une avec  omavoi dict add <entendu> <voulu>",
      "dict.addnames": "Ajoutes-en plusieurs d'un coup avec  omavoi names add <nom> <nom> …",

      // ---- settings
      "set.ptt": "maintenir pour parler",
      "set.toggle": "bascule",
      "set.dwell.always": "toujours",
      "set.dwell.changed": "si modifié",
      "set.dwell.never": "jamais",
      "set.hotkey": "RACCOURCI",
      "set.key": "touche",
      "set.behaviour": "comportement",
      "set.hotkeynote": "Lue depuis evdev, sous xkb, pour que la touche reste là où elle est physiquement même si ta disposition la remappe. Impossible d'associer un modificateur dans Hyprland à la place : appuyer dessus change le modmask, ce qui déclenche aussitôt le raccourci de relâchement et enregistre une prise de 0,0 s.",
      "set.audio": "AUDIO",
      "set.preroll": "pré-enregistrement",
      "set.prerollwhy": "Audio conservé d'avant l'appui sur la touche. Réduis-le et la première syllabe commence à manquer pendant que PipeWire ouvre le flux.",
      "set.tail": "traîne",
      "set.warnbelow": "alerter en dessous de",
      "set.maxtake": "prise max",
      "set.hud": "HUD",
      "set.keepup": "laisser le résultat affiché",
      "set.hudnote": "« changed » est la valeur par défaut : une temporisation que tu paies toujours devient du bruit dès que tu dictes deux phrases de suite, mais une correction silencieuse que tu n'as jamais vue est pire.",
      "set.notifications": "notifications",
      "set.on": "activé",
      "set.off": "désactivé",
      "set.history": "HISTORIQUE",
      "set.keepaudio": "garder l'audio pour",
      "set.takes": " prises",
      "set.historynote": "L'audio stocké est ce qui rend possible de rejouer une prise sur un autre modèle, et l'essai à blanc des noms. Mets-le à 0 et les deux disparaissent avec.",
      "set.privacy": "OÙ VA TA VOIX",
      "set.neverleaves": "L'audio ne quitte jamais cette machine",
      "set.privacynote": "La reconnaissance vocale tourne sur le GPU local dans tous les modes. Un mode dont l'étape LLM est un modèle distant, lui, envoie le texte transcrit dehors — l'onglet Modes montre lesquels ont une étape.",
      "set.editconfig": "Modifier la configuration",
      "set.restart": "Redémarrer le démon",
      "set.configpath": "tout ici est  ~/.config/omavoi/config.toml"
    },
    es: {
      // ---- nav
      "nav.history": "Historial",
      "nav.modes": "Modos",
      "nav.models": "Modelos",
      "nav.dictionary": "Diccionario",
      "nav.settings": "Ajustes",
      "lang.label": "Idioma",

      // ---- state
      "state.ready": "Listo",
      "state.idle": "inactivo",
      "state.recording": "grabando",
      "state.transcribing": "transcribiendo",
      "state.stopped": "demonio detenido",

      // ---- setup
      "setup.prefix": "instalación ",
      "setup.title": "Faltan dos piezas por instalar",
      "setup.blurb": "Aquí no se ejecuta nada hasta que lo pulses, y cada paso muestra primero el comando exacto. Omarchy no ejecuta nada desde una carpeta de plugin a propósito, así que esta pantalla pregunta.",
      "setup.optional": "opcional",
      "setup.copy": "Copiar",
      "setup.run": "Ejecutar",
      "setup.recheck": "Volver a comprobar",
      "setup.hint": "o ejecuta  omavoi setup  en una terminal — los mismos pasos, el mismo orden",

      // ---- history
      "hist.none": "todavía no hay tomas — mantén %1 y habla",
      "hist.yourkey": "tu tecla",
      "hist.dropped": "descartada — ",
      "hist.audio": "audio",
      "hist.level": "nivel",
      "hist.decode": "decodificación",
      "hist.model": "modelo",
      "hist.language": "idioma",
      "hist.mode": "modo",
      "hist.injected": "insertado por",
      "hist.said": "el modelo dijo:  ",
      "hist.post": "POSPROCESADO",
      "hist.segments": "CONFIANZA POR SEGMENTO",
      "hist.copy": "Copiar",
      "hist.play": "Reproducir",

      // ---- modes
      "modes.wontfit": "necesita %1 libres",
      "modes.blocked": "no se cambió — el modelo de este modo no cabe ahora en la VRAM",
      "modes.newname": "nombre del nuevo modo",
      "modes.here": "aquí",
      "modes.fallback": "por defecto",
      "modes.followwin": "El modo sigue a la ventana enfocada",
      "modes.everytake": "Cada toma usa ",
      "modes.longestwins": "Gana la coincidencia más larga de abajo; si nada coincide, se vuelve a default.",
      "modes.matchoff": "La coincidencia por ventana está desactivada, así que las listas de abajo están configuradas pero inertes. Hay que ajustarla aplicación por aplicación antes de que valga la pena.",
      "modes.following": "sigue a la ventana",
      "modes.fixed": "fijo",
      "modes.activehere": "activo en esta ventana",
      "modes.delete": "Eliminar modo",
      "modes.opens": "SE ABRE EN",
      "modes.notinuse": "sin uso mientras el modo esté fijo",
      "modes.nothing": "nada — a este modo solo se llega por su nombre",
      "modes.classph": "clase de ventana, p. ej. thunderbird",
      "modes.add": "Añadir",
      "modes.matchhint": "Se compara con la clase y el título de Hyprland. Gana la coincidencia más larga.",
      "modes.s1": "1  VOZ",
      "modes.speechsub": "lo que se le dice al modelo antes de decodificar",
      "modes.language": "idioma",
      "modes.langhint": "en blanco lo detecta en cada toma; un código como en o zh es más rápido y más estable",
      "modes.decoderhint": "pista para el decodificador",
      "modes.promptph": "Se le pasa al modelo. Va bien para la jerga que siempre destroza — es una pista, no una garantía; la garantía es el diccionario.",
      "modes.s2": "2  REGLAS",
      "modes.rulessub": "determinista · sin latencia",
      "modes.r.hallucinations": "alucinaciones",
      "modes.r.fillers": "muletillas",
      "modes.r.dictionary": "diccionario",
      "modes.r.names": "nombres",
      "modes.r.cjk": "espaciado CJK",
      "modes.keeppunct": "conservar la puntuación final",
      "modes.s3": "3  LLM",
      "modes.llmsub": "opcional · se ejecuta en orden · un fallo conserva el texto recibido",
      "modes.step": "paso ",
      "modes.stepsuffix": "",
      "modes.remove": "Quitar",
      "modes.stepph": "Dile que edite, no que responda.",
      "modes.nostep": "Este modo no tiene pasada de LLM, así que todavía no hay prompt que escribir. Añade una abajo y su prompt aparecerá aquí, editable y ya con un valor por defecto utilizable.",
      "modes.addstep": "+ añadir un paso",
      "modes.nollm": "no hay ningún LLM configurado — mira la pestaña Modelos",
      "modes.inject.auto": "auto",
      "modes.inject.clipboard": "portapapeles",
      "modes.langauto": "auto",
      "modes.s4": "4  INSERCIÓN",
      "modes.injecthint": "auto escribe con wtype, salvo en clientes XWayland y aplicaciones Electron conocidas, donde pega en su lugar — allí los keycodes sintéticos de wtype llegan como dígitos.",

      // ---- models
      "models.speech": "VOZ",
      "models.speechsub": "audio → texto · se ejecuta uno",
      "models.e.vulkan": "Local · Vulkan",
      "models.e.vulkan.sub": "whisper.cpp · pesos ggml · NVIDIA, AMD e Intel por igual",
      "models.e.vulkan.note": "~10 MB de paquetes",
      "models.e.cuda": "Local · CUDA",
      "models.e.cuda.sub": "faster-whisper · pesos ct2 · solo NVIDIA",
      "models.e.cuda.note": "~2,2 GB de wheels",
      "models.e.api": "API remota",
      "models.e.api.sub": "compatible con OpenAI · OpenAI, Groq, SiliconFlow, un servidor local",
      "models.e.api.note": "el audio sale de esta máquina",
      "models.llmcathint": "lo nombra un paso de un modo, no es un cambio global",
      "models.now": "EN EJECUCIÓN",
      "models.running": "en ejecución",
      "models.notloaded": "sin cargar",
      "models.cold": "en frío · arranca al primer uso",
      "models.ready": "listo",
      "models.nodaemon": "no se alcanza el demonio — no se sabe qué está cargado",
      "models.stale": "El demonio sigue ejecutando con lo que arrancó",
      "models.loaded": "cargado ",
      "models.configured": "configurado ",
      "models.restart": "Reiniciar el demonio",
      "models.list": "MODELOS · ",
      "models.formathint": "el formato que ejecuta este motor",
      "models.ondisk": "ya está en disco",
      "models.downloading": "descargando…",
      "models.download": "Descargar",
      "models.use": "Usar",
      "models.remove": "Eliminar",
      "models.ourstore": "nuestro almacén",
      "models.outside": "Los pesos que se encuentran fuera de %1 se usan donde están y nunca se borran.",
      "models.llm": "LLM",
      "models.llmsub": "texto → texto · cuantos quieras, los modos los llaman por su nombre",
      "models.remote": "remoto",
      "models.local": "local",
      "models.nokey": "sin clave",
      "models.usedby": "usado por ",
      "models.unused": "ningún modo lo nombra — no cuesta nada hasta que alguno lo haga",
      "models.endpointnote": "Los endpoints viven bajo [llm.<name>] — omavoi config edit. Una clave nunca va en la configuración: define su variable de entorno, o ponla en secrets.toml.",
      "models.vram": "VRAM · ",
      "models.seg.speech": "modelo de voz",
      "models.seg.other": "otros programas",
      "models.seg.free": "libre",
      "models.vramsub": "en uso en toda la máquina",
      "models.needs": "necesita",
      "models.vramnote": "Mantener los dos residentes es justamente el punto: una cadena que carga pesos en cada toma cuesta segundos, no milisegundos. Si te pasas, lo que se desaloja es el modelo de voz — el dictado va diez veces más lento sin que nada diga por qué.",

      // ---- dictionary
      "dict.rules": "reglas",
      "dict.names": "nombres",
      "dict.blurb": "oído → querido. Un prompt de decodificador es una pista que el modelo puede ignorar; esto es la garantía. Se prueba primero la clave más larga, así que una más corta contenida en ella nunca se dispara.",
      "dict.shadowed": "nunca se dispara — la tapa ",
      "dict.remove": "Quitar",
      "dict.namesblurb": "Escribe solo la forma correcta. Los nombres se meten en el prompt del decodificador para que el modelo los produzca, y luego se emparejan por sonido para que los homófonos vuelvan al sitio. El emparejamiento sigue desactivado hasta que se haya mirado una prueba en seco — es lo único aquí que puede estropear texto que ya estaba bien.",
      "dict.matching": "emparejando",
      "dict.seedonly": "solo prompt",
      "dict.dryrun": "Prueba en seco",
      "dict.enable": "Activar emparejamiento",
      "dict.prompt": "prompt: ",
      "dict.none": "(ninguno)",
      "dict.addrule": "Añade una con  omavoi dict add <oído> <querido>",
      "dict.addnames": "Añade varios de golpe con  omavoi names add <nombre> <nombre> …",

      // ---- settings
      "set.ptt": "mantener para hablar",
      "set.toggle": "alternar",
      "set.dwell.always": "siempre",
      "set.dwell.changed": "si cambió",
      "set.dwell.never": "nunca",
      "set.hotkey": "ATAJO",
      "set.key": "tecla",
      "set.behaviour": "comportamiento",
      "set.hotkeynote": "Se lee desde evdev, por debajo de xkb, así que la tecla se queda donde está físicamente aunque tu distribución la remapee. No se puede asignar un modificador en Hyprland en su lugar: pulsarlo cambia el modmask, lo que dispara al instante el atajo de suelta y graba una toma de 0,0 s.",
      "set.audio": "AUDIO",
      "set.preroll": "pre-grabación",
      "set.prerollwhy": "Audio guardado de antes de pulsar la tecla. Bájalo y la primera sílaba empieza a perderse mientras PipeWire abre el flujo.",
      "set.tail": "cola",
      "set.warnbelow": "avisar por debajo de",
      "set.maxtake": "toma máxima",
      "set.hud": "HUD",
      "set.keepup": "mantener el resultado visible",
      "set.hudnote": "«changed» es el valor por defecto: una espera que pagas siempre se convierte en ruido en cuanto dictas dos frases seguidas, pero una corrección silenciosa que nunca viste es peor.",
      "set.notifications": "notificaciones",
      "set.on": "activado",
      "set.off": "desactivado",
      "set.history": "HISTORIAL",
      "set.keepaudio": "guardar audio de",
      "set.takes": " tomas",
      "set.historynote": "El audio guardado es lo que permite volver a pasar una toma por otro modelo, y la prueba en seco de los nombres. Ponlo a 0 y ambas cosas se van con él.",
      "set.privacy": "ADÓNDE VA TU VOZ",
      "set.neverleaves": "El audio nunca sale de esta máquina",
      "set.privacynote": "El reconocimiento de voz corre en la GPU local en todos los modos. Un modo cuyo paso de LLM sea un modelo remoto sí envía fuera el texto transcrito — la pestaña Modos muestra cuáles tienen algún paso.",
      "set.editconfig": "Editar la configuración",
      "set.restart": "Reiniciar el demonio",
      "set.configpath": "todo esto está en  ~/.config/omavoi/config.toml"
    },
    ja: {
      // ---- nav
      "nav.history": "履歴",
      "nav.modes": "モード",
      "nav.models": "モデル",
      "nav.dictionary": "辞書",
      "nav.settings": "設定",
      "lang.label": "言語",

      // ---- state
      "state.ready": "準備完了",
      "state.idle": "待機中",
      "state.recording": "録音中",
      "state.transcribing": "文字起こし中",
      "state.stopped": "デーモン停止",

      // ---- setup
      "setup.prefix": "セットアップ ",
      "setup.title": "あと二つインストールが必要です",
      "setup.blurb": "ここでは押すまで何も実行されず、各ステップは実行前に正確なコマンドを表示します。Omarchy はプラグインフォルダの中身を意図的に一切実行しないので、この画面が代わりに尋ねます。",
      "setup.optional": "任意",
      "setup.copy": "コピー",
      "setup.run": "実行",
      "setup.recheck": "再確認",
      "setup.hint": "またはターミナルで  omavoi setup  を実行 —— 手順も順序も同じです",

      // ---- history
      "hist.none": "まだ録音がありません —— %1 を押しながら話してください",
      "hist.yourkey": "設定したキー",
      "hist.dropped": "破棄 —— ",
      "hist.audio": "音声",
      "hist.level": "レベル",
      "hist.decode": "デコード",
      "hist.model": "モデル",
      "hist.language": "言語",
      "hist.mode": "モード",
      "hist.injected": "入力方法",
      "hist.said": "モデルの出力：  ",
      "hist.post": "後処理",
      "hist.segments": "セグメント信頼度",
      "hist.copy": "コピー",
      "hist.play": "再生",

      // ---- modes
      "modes.wontfit": "空き %1 が必要",
      "modes.blocked": "切り替えていません —— このモードのモデルは今の VRAM に収まりません",
      "modes.newname": "新しいモード名",
      "modes.here": "現在",
      "modes.fallback": "フォールバック",
      "modes.followwin": "モードはフォーカス中のウィンドウに追従します",
      "modes.everytake": "毎回このモードを使用： ",
      "modes.longestwins": "下で最も長く一致したものが勝ちます。何も一致しなければ default に戻ります。",
      "modes.matchoff": "ウィンドウ照合は無効なので、下のリストは設定済みでも動作しません。役に立つまでにはアプリごとの調整が必要です。",
      "modes.following": "ウィンドウに追従",
      "modes.fixed": "固定",
      "modes.activehere": "このウィンドウで有効",
      "modes.delete": "モードを削除",
      "modes.opens": "起動条件",
      "modes.notinuse": "モードが固定の間は使われません",
      "modes.nothing": "なし —— このモードは名前でしか呼び出せません",
      "modes.classph": "ウィンドウクラス（例：thunderbird）",
      "modes.add": "追加",
      "modes.matchhint": "Hyprland のクラスとタイトルに照合します。最も長い一致が勝ちます。",
      "modes.s1": "1  音声",
      "modes.speechsub": "デコード前にモデルへ伝える内容",
      "modes.language": "言語",
      "modes.langhint": "空欄なら毎回自動判定。en や zh のようなコードを指定すると速く安定します",
      "modes.decoderhint": "デコーダーへのヒント",
      "modes.promptph": "モデルに渡されます。いつも崩れる専門用語に有効 —— これはヒントで保証ではありません。保証するのは辞書です。",
      "modes.s2": "2  ルール",
      "modes.rulessub": "決定的 · 遅延なし",
      "modes.r.hallucinations": "幻覚除去",
      "modes.r.fillers": "フィラー",
      "modes.r.dictionary": "辞書",
      "modes.r.names": "固有名詞",
      "modes.r.cjk": "CJK 空白",
      "modes.keeppunct": "文末の句読点を残す",
      "modes.s3": "3  LLM",
      "modes.llmsub": "任意 · 順番に実行 · 失敗すると渡されたテキストをそのまま保持",
      "modes.step": "ステップ ",
      "modes.stepsuffix": "",
      "modes.remove": "削除",
      "modes.stepph": "回答ではなく編集をさせる指示を書いてください。",
      "modes.nostep": "このモードには LLM の処理がないので、まだ書くプロンプトがありません。下で追加すると、そのプロンプトがここに現れ、編集できます。使える初期値が最初から入っています。",
      "modes.addstep": "+ ステップを追加",
      "modes.nollm": "LLM が未設定です —— 「モデル」タブを確認してください",
      "modes.inject.auto": "自動",
      "modes.inject.clipboard": "クリップボード",
      "modes.langauto": "自動",
      "modes.s4": "4  入力",
      "modes.injecthint": "自動では wtype で打鍵しますが、XWayland クライアントと既知の Electron アプリでは貼り付けに切り替えます —— wtype の合成キーコードはそれらには数字として届くためです。",

      // ---- models
      "models.speech": "音声",
      "models.speechsub": "音声 → テキスト · 動くのは一つだけ",
      "models.e.vulkan": "ローカル · Vulkan",
      "models.e.vulkan.sub": "whisper.cpp · ggml 重み · NVIDIA、AMD、Intel いずれでも",
      "models.e.vulkan.note": "パッケージ約 10 MB",
      "models.e.cuda": "ローカル · CUDA",
      "models.e.cuda.sub": "faster-whisper · ct2 重み · NVIDIA 限定",
      "models.e.cuda.note": "wheel 約 2.2 GB",
      "models.e.api": "リモート API",
      "models.e.api.sub": "OpenAI 互換 · OpenAI、Groq、SiliconFlow、ローカルサーバー",
      "models.e.api.note": "音声がこの端末から出ます",
      "models.llmcathint": "モードのステップが名前で呼び出します。全体の切り替えではありません",
      "models.now": "稼働中",
      "models.running": "稼働中",
      "models.notloaded": "未ロード",
      "models.cold": "停止中 · 初回利用時に起動",
      "models.ready": "準備完了",
      "models.nodaemon": "デーモンに接続できません —— 何がロードされているか不明です",
      "models.stale": "デーモンは起動時に読み込んだものをまだ使っています",
      "models.loaded": "読み込み済み ",
      "models.configured": "設定済み ",
      "models.restart": "デーモンを再起動",
      "models.list": "モデル · ",
      "models.formathint": "このエンジンが扱う形式",
      "models.ondisk": "ディスクに既にあります",
      "models.downloading": "ダウンロード中…",
      "models.download": "ダウンロード",
      "models.use": "使用",
      "models.remove": "削除",
      "models.ourstore": "こちらの保存先",
      "models.outside": "%1 の外で見つかった重みはその場所のまま使われ、削除されることはありません。",
      "models.llm": "LLM",
      "models.llmsub": "テキスト → テキスト · 数はいくつでも、モードが名前で呼び出します",
      "models.remote": "リモート",
      "models.local": "ローカル",
      "models.nokey": "キーなし",
      "models.usedby": "使用中のモード： ",
      "models.unused": "どのモードからも呼ばれていません —— 呼ばれるまで負荷はゼロです",
      "models.endpointnote": "エンドポイントは [llm.<name>] の下にあります —— omavoi config edit。キーは決して設定ファイルに書きません。環境変数に設定するか、secrets.toml に置いてください。",
      "models.vram": "VRAM · ",
      "models.seg.speech": "音声モデル",
      "models.seg.other": "他のプログラム",
      "models.seg.free": "空き",
      "models.vramsub": "端末全体での使用量",
      "models.needs": "必要",
      "models.vramnote": "両方を常駐させることが肝心です。録音ごとに重みを読み込む構成ではミリ秒ではなく秒単位のコストがかかります。詰め込みすぎると追い出されるのは音声モデルの側で —— 理由を告げるものが何もないまま、入力が十倍遅くなります。",

      // ---- dictionary
      "dict.rules": "ルール",
      "dict.names": "固有名詞",
      "dict.blurb": "聞こえた語 → 本来の語。デコーダーのプロンプトはモデルが無視できる助言にすぎませんが、こちらは保証です。照合は最も長いキーから試すので、それに含まれる短いキーは決して発火しません。",
      "dict.shadowed": "決して発火しません —— 次のキーに隠れています： ",
      "dict.remove": "削除",
      "dict.namesblurb": "正しい表記だけを書いてください。固有名詞はデコーダーのプロンプトに入れてモデルがその形を出すようにし、その後で音の近さで照合して同音の表記を引き戻します。照合はドライランを確認するまで無効のままです —— ここで唯一、すでに正しいテキストを壊しうる機能だからです。",
      "dict.matching": "照合中",
      "dict.seedonly": "プロンプトのみ",
      "dict.dryrun": "ドライラン",
      "dict.enable": "照合を有効化",
      "dict.prompt": "プロンプト： ",
      "dict.none": "（なし）",
      "dict.addrule": "追加するには  omavoi dict add <聞こえた語> <本来の語>",
      "dict.addnames": "まとめて追加するには  omavoi names add <名前> <名前> …",

      // ---- settings
      "set.ptt": "押している間だけ話す",
      "set.toggle": "押して切り替え",
      "set.dwell.always": "常に",
      "set.dwell.changed": "変化したとき",
      "set.dwell.never": "しない",
      "set.hotkey": "ホットキー",
      "set.key": "キー",
      "set.behaviour": "動作",
      "set.hotkeynote": "xkb より下の evdev から直接読むので、キーボード配列で再割り当てしてもキーは物理的な位置のままです。代わりに Hyprland で修飾キーを割り当てることはできません。修飾キーを押すと modmask が変わり、離したときのバインドが即座に発火して 0.0 秒の録音になります。",
      "set.audio": "音声",
      "set.preroll": "先読みバッファ",
      "set.prerollwhy": "キーを押す前の音声を保持します。小さくすると、PipeWire がストリームを開く間に最初の音節が欠け始めます。",
      "set.tail": "末尾の余裕",
      "set.warnbelow": "この値未満で警告",
      "set.maxtake": "一回の上限",
      "set.hud": "HUD",
      "set.keepup": "結果を表示したままにする",
      "set.hudnote": "既定は「changed」です。毎回必ず表示を待つ設定は、二文続けて話した瞬間に邪魔になります。とはいえ、見ないまま静かに書き換えられるほうが厄介です。",
      "set.notifications": "通知",
      "set.on": "オン",
      "set.off": "オフ",
      "set.history": "履歴",
      "set.keepaudio": "音声を保持する件数",
      "set.takes": " 件",
      "set.historynote": "保存した音声があるからこそ、別のモデルで録音を再実行することも、固有名詞のドライランもできます。0 にすると、その両方が一緒に失われます。",
      "set.privacy": "あなたの声はどこへ行くか",
      "set.neverleaves": "音声はこの端末から出ません",
      "set.privacynote": "音声認識はどのモードでもローカルの GPU で動きます。ただし LLM ステップにリモートモデルを使うモードは、文字起こししたテキストを外へ送ります —— どのモードにステップがあるかは「モード」タブで確認できます。",
      "set.editconfig": "設定を編集",
      "set.restart": "デーモンを再起動",
      "set.configpath": "ここのすべては  ~/.config/omavoi/config.toml にあります"
    },
    vi: {
      // ---- nav
      "nav.history": "Lịch sử",
      "nav.modes": "Chế độ",
      "nav.models": "Mô hình",
      "nav.dictionary": "Từ điển",
      "nav.settings": "Cài đặt",
      "lang.label": "Ngôn ngữ",

      // ---- state
      "state.ready": "Sẵn sàng",
      "state.idle": "rảnh",
      "state.recording": "đang ghi",
      "state.transcribing": "đang chuyển thành chữ",
      "state.stopped": "dịch vụ đã dừng",

      // ---- setup
      "setup.prefix": "cài đặt ",
      "setup.title": "Còn hai phần nữa cần cài",
      "setup.blurb": "Ở đây không có gì chạy cho đến khi bạn bấm, và mỗi bước đều hiện đúng câu lệnh trước. Omarchy cố tình không chạy bất cứ thứ gì từ trong thư mục plugin, nên màn hình này phải hỏi bạn.",
      "setup.optional": "không bắt buộc",
      "setup.copy": "Sao chép",
      "setup.run": "Chạy",
      "setup.recheck": "Kiểm tra lại",
      "setup.hint": "hoặc chạy  omavoi setup  trong terminal — cùng các bước, cùng thứ tự",

      // ---- history
      "hist.none": "chưa có bản ghi nào — giữ %1 và nói",
      "hist.yourkey": "phím của bạn",
      "hist.dropped": "đã bỏ — ",
      "hist.audio": "âm thanh",
      "hist.level": "mức",
      "hist.decode": "giải mã",
      "hist.model": "mô hình",
      "hist.language": "ngôn ngữ",
      "hist.mode": "chế độ",
      "hist.injected": "cách chèn",
      "hist.said": "mô hình nghe thành:  ",
      "hist.post": "HẬU XỬ LÝ",
      "hist.segments": "ĐỘ TIN CẬY TỪNG ĐOẠN",
      "hist.copy": "Sao chép",
      "hist.play": "Phát",

      // ---- modes
      "modes.wontfit": "cần %1 trống",
      "modes.blocked": "chưa chuyển — mô hình của chế độ này hiện không vừa VRAM",
      "modes.newname": "tên chế độ mới",
      "modes.here": "hiện tại",
      "modes.fallback": "dự phòng",
      "modes.followwin": "Chế độ đi theo cửa sổ đang được chọn",
      "modes.everytake": "Mọi bản ghi đều dùng ",
      "modes.longestwins": "Mẫu khớp dài nhất bên dưới thắng; không khớp gì thì quay về default.",
      "modes.matchoff": "Việc khớp theo cửa sổ đang tắt, nên các danh sách bên dưới đã được cấu hình nhưng không có tác dụng. Nó cần được tinh chỉnh cho từng ứng dụng trước khi đáng dùng.",
      "modes.following": "đi theo cửa sổ",
      "modes.fixed": "cố định",
      "modes.activehere": "đang dùng trong cửa sổ này",
      "modes.delete": "Xóa chế độ",
      "modes.opens": "MỞ KHI",
      "modes.notinuse": "không dùng khi chế độ đang cố định",
      "modes.nothing": "không có — chế độ này chỉ gọi được bằng tên",
      "modes.classph": "class cửa sổ, ví dụ thunderbird",
      "modes.add": "Thêm",
      "modes.matchhint": "Đối chiếu với class và title của Hyprland. Mẫu khớp dài nhất thắng.",
      "modes.s1": "1  GIỌNG NÓI",
      "modes.speechsub": "những gì mô hình được cho biết trước khi giải mã",
      "modes.language": "ngôn ngữ",
      "modes.langhint": "để trống thì tự nhận mỗi lần; đặt mã như en hay zh sẽ nhanh và ổn định hơn",
      "modes.decoderhint": "gợi ý cho bộ giải mã",
      "modes.promptph": "Được đưa vào mô hình. Hữu ích với thuật ngữ mà nó cứ nghe sai — đây là gợi ý, không phải bảo đảm; thứ bảo đảm là từ điển.",
      "modes.s2": "2  QUY TẮC",
      "modes.rulessub": "tất định · không thêm độ trễ",
      "modes.r.hallucinations": "câu bịa",
      "modes.r.fillers": "từ đệm",
      "modes.r.dictionary": "từ điển",
      "modes.r.names": "tên riêng",
      "modes.r.cjk": "khoảng cách CJK",
      "modes.keeppunct": "giữ dấu câu ở cuối",
      "modes.s3": "3  LLM",
      "modes.llmsub": "không bắt buộc · chạy theo thứ tự · nếu lỗi thì giữ nguyên văn bản nhận được",
      "modes.step": "bước ",
      "modes.stepsuffix": "",
      "modes.remove": "Bỏ",
      "modes.stepph": "Hãy bảo nó sửa văn bản, đừng để nó trả lời.",
      "modes.nostep": "Chế độ này không có bước LLM nào, nên chưa có prompt để viết. Thêm một bước bên dưới thì prompt của nó sẽ hiện ở đây, sửa được, và đã có sẵn một giá trị mặc định dùng được.",
      "modes.addstep": "+ thêm một bước",
      "modes.nollm": "chưa cấu hình LLM nào — xem thẻ Mô hình",
      "modes.inject.auto": "tự động",
      "modes.inject.clipboard": "clipboard",
      "modes.langauto": "tự động",
      "modes.s4": "4  CHÈN CHỮ",
      "modes.injecthint": "tự động sẽ gõ bằng wtype, trừ các client XWayland và những ứng dụng Electron đã biết, ở đó nó dán thay vì gõ — keycode tổng hợp của wtype đến những ứng dụng đó dưới dạng chữ số.",

      // ---- models
      "models.speech": "GIỌNG NÓI",
      "models.speechsub": "âm thanh → chữ · chỉ một cái chạy",
      "models.e.vulkan": "Cục bộ · Vulkan",
      "models.e.vulkan.sub": "whisper.cpp · trọng số ggml · NVIDIA, AMD và Intel đều được",
      "models.e.vulkan.note": "khoảng 10 MB gói",
      "models.e.cuda": "Cục bộ · CUDA",
      "models.e.cuda.sub": "faster-whisper · trọng số ct2 · chỉ NVIDIA",
      "models.e.cuda.note": "khoảng 2,2 GB wheel",
      "models.e.api": "API từ xa",
      "models.e.api.sub": "tương thích OpenAI · OpenAI, Groq, SiliconFlow, một server cục bộ",
      "models.e.api.note": "âm thanh sẽ rời khỏi máy này",
      "models.llmcathint": "được bước của một chế độ gọi theo tên, không phải chuyển toàn cục",
      "models.now": "ĐANG CHẠY",
      "models.running": "đang chạy",
      "models.notloaded": "chưa nạp",
      "models.cold": "chưa khởi động · chạy khi dùng lần đầu",
      "models.ready": "sẵn sàng",
      "models.nodaemon": "không liên lạc được dịch vụ — không rõ đang nạp những gì",
      "models.stale": "Dịch vụ vẫn đang chạy thứ nó nạp lúc khởi động",
      "models.loaded": "đã nạp ",
      "models.configured": "đã cấu hình ",
      "models.restart": "Khởi động lại dịch vụ",
      "models.list": "MÔ HÌNH · ",
      "models.formathint": "định dạng mà engine này chạy",
      "models.ondisk": "đã có trên đĩa",
      "models.downloading": "đang tải…",
      "models.download": "Tải về",
      "models.use": "Dùng",
      "models.remove": "Xóa",
      "models.ourstore": "kho của chúng ta",
      "models.outside": "Trọng số tìm thấy ngoài %1 sẽ được dùng ngay tại chỗ và không bao giờ bị xóa.",
      "models.llm": "LLM",
      "models.llmsub": "chữ → chữ · bao nhiêu cũng được, các chế độ gọi theo tên",
      "models.remote": "từ xa",
      "models.local": "cục bộ",
      "models.nokey": "chưa có khóa",
      "models.usedby": "được dùng bởi ",
      "models.unused": "chưa chế độ nào gọi tên — chưa tốn gì cho đến khi có",
      "models.endpointnote": "Các endpoint nằm dưới [llm.<name>] — omavoi config edit. Khóa không bao giờ nằm trong file cấu hình: hãy đặt biến môi trường của nó, hoặc để trong secrets.toml.",
      "models.vram": "VRAM · ",
      "models.seg.speech": "mô hình giọng nói",
      "models.seg.other": "chương trình khác",
      "models.seg.free": "còn trống",
      "models.vramsub": "đang dùng trên toàn máy",
      "models.needs": "cần",
      "models.vramnote": "Giữ cả hai thường trú mới là điểm chính: một chuỗi phải nạp trọng số mỗi lần ghi sẽ tốn hàng giây, không phải hàng mili giây. Nếu vượt quá dung lượng, thứ bị đẩy ra là mô hình giọng nói — việc nhập bằng giọng chậm đi mười lần mà không có gì nói cho bạn biết vì sao.",

      // ---- dictionary
      "dict.rules": "quy tắc",
      "dict.names": "tên riêng",
      "dict.blurb": "nghe thành → thật ra là. Prompt của bộ giải mã chỉ là gợi ý mà mô hình có thể bỏ qua; đây mới là thứ bảo đảm. Khóa dài nhất được thử trước, nên một khóa ngắn hơn nằm bên trong nó sẽ không bao giờ chạy.",
      "dict.shadowed": "không bao giờ chạy — bị che bởi ",
      "dict.remove": "Bỏ",
      "dict.namesblurb": "Chỉ viết dạng đúng. Tên riêng được đưa vào prompt của bộ giải mã để mô hình tạo ra chúng, rồi sau đó khớp theo âm để các từ đồng âm quay về đúng dạng. Việc khớp vẫn tắt cho đến khi bạn xem một lần chạy thử — đây là thứ duy nhất ở đây có thể làm hỏng văn bản vốn đã đúng.",
      "dict.matching": "đang khớp",
      "dict.seedonly": "chỉ đưa vào prompt",
      "dict.dryrun": "Chạy thử",
      "dict.enable": "Bật việc khớp",
      "dict.prompt": "prompt: ",
      "dict.none": "(không có)",
      "dict.addrule": "Thêm một mục với  omavoi dict add <nghe thành> <thật ra là>",
      "dict.addnames": "Thêm nhiều mục một lượt với  omavoi names add <tên> <tên> …",

      // ---- settings
      "set.ptt": "giữ để nói",
      "set.toggle": "bấm để bật/tắt",
      "set.dwell.always": "luôn luôn",
      "set.dwell.changed": "khi có thay đổi",
      "set.dwell.never": "không bao giờ",
      "set.hotkey": "PHÍM NÓNG",
      "set.key": "phím",
      "set.behaviour": "cách hoạt động",
      "set.hotkeynote": "Đọc trực tiếp từ evdev, nằm dưới xkb, nên phím vẫn ở đúng vị trí vật lý của nó dù bố cục bàn phím có gán lại. Không thể gán một phím modifier trong Hyprland để thay thế: bấm modifier làm modmask đổi, khiến ràng buộc lúc nhả phím chạy ngay và ghi ra một bản dài 0,0 giây.",
      "set.audio": "ÂM THANH",
      "set.preroll": "đệm trước",
      "set.prerollwhy": "Phần âm thanh giữ lại từ trước lúc bấm phím. Giảm xuống thì âm tiết đầu bắt đầu bị mất trong lúc PipeWire mở luồng.",
      "set.tail": "đệm sau",
      "set.warnbelow": "cảnh báo khi dưới",
      "set.maxtake": "dài nhất mỗi lần",
      "set.hud": "HUD",
      "set.keepup": "giữ kết quả trên màn hình",
      "set.hudnote": "Mặc định là „changed“: một khoảng chờ mà bạn luôn phải trả sẽ thành thứ gây nhiễu ngay khi bạn đọc hai câu liền nhau, nhưng một lần sửa âm thầm mà bạn không hề thấy thì tệ hơn.",
      "set.notifications": "thông báo",
      "set.on": "bật",
      "set.off": "tắt",
      "set.history": "LỊCH SỬ",
      "set.keepaudio": "giữ âm thanh cho",
      "set.takes": " bản ghi",
      "set.historynote": "Âm thanh đã lưu là thứ cho phép chạy lại một bản ghi trên mô hình khác, và chạy thử phần tên riêng. Đặt về 0 thì cả hai mất theo.",
      "set.privacy": "GIỌNG CỦA BẠN ĐI ĐÂU",
      "set.neverleaves": "Âm thanh không bao giờ rời khỏi máy này",
      "set.privacynote": "Việc nhận dạng giọng nói chạy trên GPU cục bộ ở mọi chế độ. Nhưng chế độ nào có bước LLM dùng mô hình từ xa thì đúng là gửi văn bản đã chuyển ra ngoài — thẻ Chế độ cho thấy chế độ nào có bước đó.",
      "set.editconfig": "Sửa cấu hình",
      "set.restart": "Khởi động lại dịch vụ",
      "set.configpath": "mọi thứ ở đây nằm trong  ~/.config/omavoi/config.toml"
    }
  })
}
