# -*- coding: utf-8 -*-
PACK = {
 "first.title": 'Omavoi einrichten',
 "first.blurb": 'Zwei Fragen, dann ein Knopf. Nichts läuft, bis du drückst, und jeder Befehl wird vorher gezeigt.',
 "first.pick.language": 'Sprache der Oberfläche',
 "first.pick.model": 'Sprachmodell',
 "first.reuse": 'Gewichte, die ein anderes Werkzeug hier schon abgelegt hat — dort genutzt, wo sie liegen, kein Download',
 "first.reuse.label": 'Vorhandene nutzen',
 "first.m.large": 'die Vorgabe; läuft über Vulkan auf jeder GPU',
 "first.m.turbo": 'das Leichteste, das sich noch lohnt; ein Fünftel des Downloads',
 "first.willrun": 'WAS AUSGEFÜHRT WIRD',
 "first.needspassword": 'fragt nach deinem Passwort',
 "first.install": 'Installieren',
 "first.retry": 'Erneut versuchen',
 "first.working": '%1 …',
 "first.failed": '%1 fehlgeschlagen — siehe unten',
 "first.cancelled": 'die Passwortabfrage wurde abgebrochen, es wurde nichts installiert',
 "first.done": 'Bereit — Taste halten und sprechen',
 "first.dbstale": 'Deine Paketdatenbank ist %1 Tage alt. Jetzt etwas zu installieren scheitert mit 404: die dort genannten Versionen liegen nicht mehr auf den Spiegeln. Arch braucht vor neuen Paketen ohnehin ein Systemupdate.',
 "first.updatebtn": 'Systempakete aktualisieren',
 "first.pacman404": 'Die Paketdatenbank ist veraltet, die Spiegel haben die dort genannten Versionen nicht mehr. Aktualisiere oben das System und versuche es erneut.',
 "first.pick.hotkey": 'Taste zum Sprechen',
 "first.hotkey.other": 'andere Taste, z. B. F9',
 "first.hotkey.note": 'Unterhalb deines Tastaturlayouts gelesen und nie übernommen, die Taste tut also weiter, was sie sonst tut — diese vier tun allein normalerweise nichts.',
 "first.group.needed": 'Du bist noch nicht in der Gruppe input, also kann keine Taste gelesen werden. Das erledigt der Schritt unten, wirksam beim nächsten Anmelden — bis dahin diktierst du über das Bar-Modul.',
 "first.step.hotkey": 'Tastenkürzel',
 "first.step.packages": 'Systempakete',
 "first.step.daemon": 'der Dienst',
 "first.step.language": 'Sprache',
 "first.step.weights": 'Modellgewichte',
 "first.step.use": 'Modell auswählen',
 "first.step.mode": 'Vorgabemodus',
 "first.step.service": 'Unit und Tastenkürzel',
 "up.title": 'AKTUALISIEREN',
 "up.behind": '%1 neue Commits auf dem Zweig des Plugins',
 "up.current": 'Aktuell',
 "up.unknown": 'Nicht feststellbar — das Plugin wurde nicht aus git installiert',
 "up.dirty": 'Das installierte Plugin hat lokale Änderungen und kann nicht vorspulen. Installiere es neu: omarchy plugin remove ai.bkblab.omavoi --yes && omarchy plugin add %1 --enable --yes',
 "up.run": 'Aktualisieren',
 "up.again": 'Erneut prüfen',
 "up.done": 'Aktualisiert',
 "up.step.plugin": 'das Plugin',
 "up.step.daemon": 'der Dienst',
 "up.step.restart": 'neu starten',
 "models.shared": 'Gemeinsamer Speicher · ',
 "models.sharednote": 'Diese GPU hat keinen eigenen Speicher — die Gewichte sind gewöhnliche Systemseiten, und der Balken oben ist der ganze Rechner. Beide dauerhaft im Speicher zu halten bleibt der Punkt, aber Überbuchung kostet hier Swap statt einer Verdrängung: das Diktat bleibt stehen, statt nur langsamer zu werden, und alles andere auf dem Rechner bleibt mit stehen.',
 "nav.setup": 'Einrichtung',
 "setup.rootblurb": 'Die Schritte oben, die root brauchen, lassen sich hier erledigen, in einer einzigen Passwortabfrage — polkit behandelt pacman als auth_admin, zwei Aufrufe heißen also zweimal gefragt werden. Danach wird der Daemon neu gestartet: er merkt sich eine fehlende Engine für die Lebensdauer des Prozesses, das Binary allein zu installieren würde ihn weiterhin sagen lassen, sie fehle.',
 "setup.rootrun": 'Diese installieren',
 "nav.history": "Verlauf",
 "nav.modes": "Modi",
 "nav.models": "Modelle",
 "nav.dictionary": "Wörterbuch",
 "nav.settings": "Einstellungen",
 "lang.label": "Sprache",

 "state.ready": "Bereit",
 "state.idle": "bereit",
 "state.recording": "Aufnahme",
 "state.transcribing": "Transkription",
 "state.stopped": "Dienst gestoppt",

 "setup.prefix": "Einrichtung ",
 "setup.title": "Noch zwei Teile zu installieren",
 "setup.blurb": "Hier läuft nichts, bis du es anstößt, und jeder Schritt zeigt "
                "vorher den genauen Befehl. Omarchy führt absichtlich nichts aus "
                "einem Plugin-Ordner aus, deshalb fragt dieser Bildschirm.",
 "setup.optional": "optional",
 "setup.copy": "Kopieren",
 "setup.run": "Ausführen",
 "setup.recheck": "Neu prüfen",
 "setup.hint": "oder  omavoi setup  im Terminal ausführen — gleiche Schritte, "
               "gleiche Reihenfolge",

 "hist.problems": 'WAS SCHIEFGING',
 "hist.steps": 'LLM-SCHRITTE',
 "hist.fellthrough": 'fiel durch, der vorige Text blieb',
 "hist.none": "noch keine Aufnahmen — %1 halten und sprechen",
 "hist.yourkey": "deine Taste",
 "hist.dropped": "verworfen — ",
 "hist.audio": "Audio",
 "hist.level": "Pegel",
 "hist.decode": "Dekodierung",
 "hist.model": "Modell",
 "hist.language": "Sprache",
 "hist.mode": "Modus",
 "hist.injected": "eingefügt per",
 "hist.said": "Modell sagte:  ",
 "hist.post": "NACHBEARBEITUNG",
 "hist.segments": "SEGMENT-KONFIDENZ",
 "hist.copy": "Kopieren",
 "hist.play": "Abspielen",

 "modes.wontfit": 'braucht %1 frei',
 "modes.blocked": 'nicht gewechselt — das Modell dieses Modus passt gerade nicht in den VRAM',
 "modes.speechmodel": 'Gewichte',
 "modes.speechglobal": 'was geladen ist',
 "modes.speechonly1": 'Für diese Engine ist nur ein Satz Gewichte heruntergeladen. Der Rest steht im Tab Modelle — ein kleinerer lohnt sich für Modi, in denen Geschwindigkeit mehr zählt als Genauigkeit.',
 "modes.newllm": 'HERUNTERGELADENE GEWICHTE, DIE NOCH NIEMAND NENNT',
 "modes.newname": "Name des neuen Modus",
 "modes.here": "hier",
 "modes.fallback": "Rückfall",
 "modes.followwin": "Der Modus folgt dem fokussierten Fenster",
 "modes.everytake": "Jede Aufnahme nutzt ",
 "modes.longestwins": "Die längste Übereinstimmung unten gewinnt; passt nichts, "
                      "greift default.",
 "modes.matchoff": "Fensterabgleich ist aus, die Listen unten sind also "
                   "konfiguriert, aber wirkungslos. Er will pro Anwendung "
                   "eingestellt werden, bevor er sich lohnt.",
 "modes.following": "folgt dem Fenster",
 "modes.fixed": "fest",
 "modes.activehere": "in diesem Fenster aktiv",
 "modes.delete": "Modus löschen",
 "modes.opens": "ÖFFNET BEI",
 "modes.notinuse": "nicht in Gebrauch, solange der Modus fest ist",
 "modes.nothing": "nichts — dieser Modus wird nur über seinen Namen erreicht",
 "modes.classph": "Fensterklasse, z. B. thunderbird",
 "modes.add": "Hinzufügen",
 "modes.matchhint": "Abgeglichen mit Klasse und Titel aus Hyprland. Die längste "
                    "Übereinstimmung gewinnt.",
 "modes.s1": "1  SPRACHE",
 "modes.speechsub": "was das Modell erfährt, bevor es dekodiert",
 "modes.language": "Sprache",
 "modes.langhint": "leer erkennt sie pro Aufnahme; ein Code wie en oder zh ist "
                   "schneller und stabiler",
 "modes.decoderhint": "Decoder-Hinweis",
 "modes.promptph": "Wird dem Modell mitgegeben. Gut für Fachwörter, die es immer "
                   "verstümmelt — ein Hinweis, keine Garantie; die Garantie ist "
                   "das Wörterbuch.",
 "modes.s2": "2  REGELN",
 "modes.rulessub": "deterministisch · ohne Latenz",
 "modes.r.hallucinations": "Halluzinationen",
 "modes.r.fillers": "Füllwörter",
 "modes.r.dictionary": "Wörterbuch",
 "modes.r.names": "Namen",
 "modes.r.cjk": "CJK-Abstände",
 "modes.keeppunct": "Satzzeichen am Ende behalten",
 "modes.s3": "3  LLM",
 "modes.llmsub": "optional · läuft in Reihenfolge · ein Fehlschlag behält den "
                 "erhaltenen Text",
 "modes.step": "Schritt ",
 "modes.stepsuffix": "",
 "modes.remove": "Entfernen",
 "modes.stepph": "Sag ihm, es soll bearbeiten, nicht antworten.",
 "modes.nostep": "Dieser Modus hat keinen LLM-Durchlauf, also gibt es noch keinen "
                 "Prompt zu schreiben. Füge unten einen hinzu, dann erscheint sein "
                 "Prompt hier, bearbeitbar und mit brauchbarer Vorbelegung.",
 "modes.addstep": "+ Schritt hinzufügen",
 "modes.nollm": "kein LLM konfiguriert — siehe Tab Modelle",
 "modes.inject.auto": "auto",
 "modes.inject.clipboard": "Zwischenablage",
 "modes.langauto": "auto",
 "modes.s4": "4  EINFÜGEN",
 "modes.injecthint": "auto tippt mit wtype, außer in XWayland-Clients und bekannten "
                     "Electron-Apps, wo es stattdessen einfügt — dort kommen die "
                     "synthetischen Keycodes von wtype als Ziffern an.",

 "models.speech": "SPRACHE",
 "models.speechsub": "Audio → Text · eines läuft",
 "models.e.vulkan": "Lokal · Vulkan",
 "models.e.vulkan.sub": "whisper.cpp · ggml-Gewichte · NVIDIA, AMD und Intel gleichermaßen",
 "models.e.vulkan.note": "~10 MB Pakete",
 "models.e.cuda": "Lokal · CUDA",
 "models.e.cuda.sub": "faster-whisper · ct2-Gewichte · nur NVIDIA",
 "models.e.cuda.note": "~2,2 GB Wheels",
 "models.e.api": "Remote-API",
 "models.e.api.sub": "OpenAI-kompatibel · OpenAI, Groq, SiliconFlow, ein lokaler Server",
 "models.e.api.note": "Audio verlässt diesen Rechner",
 "models.llmcathint": 'von einem Modus-Schritt genannt, nicht global umgeschaltet',
 "models.now": "LÄUFT JETZT",
 "models.running": "läuft",
 "models.notloaded": "nicht geladen",
 "models.coldshort": 'kalt',
 "models.cold": "kalt · startet beim ersten Gebrauch",
 "models.ready": "bereit",
 "models.nodaemon": "Dienst nicht erreichbar — was geladen ist, ist unbekannt",
 "models.col.name": 'EINTRAG',
 "models.col.model": 'MODELL',
 "models.col.engine": 'ENGINE',
 "models.col.state": 'ZUSTAND',
 "models.col.usedby": 'GENUTZT VON',
 "models.f.edit": 'Bearbeiten',
 "models.f.close": 'Schließen',
 "models.f.url": 'URL',
 "models.f.model": 'Modell',
 "models.f.key": 'Key',
 "models.f.key.place": 'hier einfügen — kommt in secrets.toml, nie in die Konfiguration',
 "models.f.key.save": 'Speichern',
 "models.f.key.saved": 'in secrets.toml gespeichert, 0600',
 "models.f.key.failed": 'konnte nicht gespeichert werden',
 "models.f.test": 'Testen',
 "models.f.testing": 'frage den Endpunkt nach seinen Modellen …',
 "models.f.testok": 'geantwortet, %1 Modelle — wähle unten eines',
 "models.k.agent": 'System-Agent',
 "models.k.agent.sub": 'der Coding-Agent, auf den Omarchy gesetzt ist — bereits angemeldet, kein Key, Sekunden Startzeit pro Aufnahme',
 "models.k.local": 'Lokales Modell',
 "models.k.local.sub": 'llama.cpp, hier gestartet und verwaltet; ein Schritt kann eigene Gewichte aus dem Katalog unten nennen',
 "models.k.api": 'Remote-API',
 "models.k.api.sub": 'OpenAI-kompatibel, und die einzige, die deine Worte vom Rechner schickt — base_url und Key setzen',
 "models.k.unset": 'nicht konfiguriert',
 "models.stale": "Der Dienst läuft noch mit dem, womit er gestartet ist",
 "models.loaded": "geladen ",
 "models.configured": "konfiguriert ",
 "models.restart": "Dienst neu starten",
 "models.list": "MODELLE · ",
 "models.formathint": "das Format, das diese Engine ausführt",
 "models.ondisk": "schon auf der Platte",
 "models.downloading": "wird geladen…",
 "models.download": "Herunterladen",
 "models.use": "Verwenden",
 "models.remove": "Entfernen",
 "models.ourstore": "unserem Speicher",
 "models.outside": "Gewichte außerhalb von %1 werden dort genutzt, wo sie liegen, "
                   "und nie gelöscht.",
 "models.llm": "LLM",
 "models.llmsub": "Text → Text · beliebig viele, von Modi namentlich aufgerufen",
 "models.remote": "remote",
 "models.local": "lokal",
 "models.nokey": "kein Key",
 "models.usedby": "genutzt von ",
 "models.unused": "von keinem Modus genannt — kostet nichts, bis einer es tut",
 "models.endpointnote": "Endpunkte stehen unter [llm.<name>] — omavoi config edit. "
                        "Ein Key kommt nie in die Konfiguration: setze seine "
                        "Umgebungsvariable oder lege ihn in secrets.toml.",
 "models.vram": "VRAM · ",
 "models.seg.speech": 'Sprachmodell',
 "models.seg.other": 'andere Programme',
 "models.seg.free": 'frei',
 "models.vramsub": "im gesamten Rechner belegt",
 "models.needs": "braucht",
 "models.vramnote": "Beide dauerhaft im Speicher zu halten ist der Punkt: eine Kette, "
                    "die Gewichte pro Aufnahme lädt, kostet Sekunden statt "
                    "Millisekunden. Bei Überbuchung wird das Sprachmodell verdrängt "
                    "— das Diktat wird zehnmal langsamer, ohne dass etwas sagt warum.",

 "dict.rules": "Regeln",
 "dict.names": "Namen",
 "dict.blurb": "gehört → gemeint. Ein Decoder-Prompt ist ein Hinweis, den das Modell "
               "ignorieren darf; hier steht die Garantie. Der längste Schlüssel wird "
               "zuerst probiert, ein darin enthaltener kürzerer greift also nie.",
 "dict.shadowed": "greift nie — verdeckt von ",
 "dict.remove": "Entfernen",
 "dict.namesblurb": "Schreibe nur die richtige Form. Namen gehen in den Decoder-Prompt, "
                    "damit das Modell sie erzeugt, und werden danach klanglich "
                    "abgeglichen, damit Homophone zurückfallen. Der Abgleich bleibt aus, "
                    "bis ein Probelauf angesehen wurde — er ist das Einzige hier, das "
                    "schon richtigen Text beschädigen kann.",
 "dict.matching": "Abgleich",
 "dict.seedonly": "nur Prompt",
 "dict.dryrun": "Probelauf",
 "dict.enable": "Abgleich aktivieren",
 "dict.prompt": "Prompt: ",
 "dict.none": "(keiner)",
 "dict.addrule": "Eine anlegen mit  omavoi dict add <gehört> <gemeint>",
 "dict.addnames": "Mehrere auf einmal mit  omavoi names add <Name> <Name> …",

 "set.ptt": "Halten zum Sprechen",
 "set.toggle": "Umschalten",
 "set.dwell.always": "immer",
 "set.dwell.changed": "bei Änderung",
 "set.dwell.never": "nie",
 "set.hotkey": "TASTENKÜRZEL",
 "set.key.rebind": 'Taste drücken',
 "set.key.press": 'warte — jetzt drücken',
 "set.key": "Taste",
 "set.behaviour": "Verhalten",
 "set.key.check": 'Erneut prüfen',
 "set.key.ok": 'hört auf %1',
 "set.key.testing": 'prüfe …',
 "set.key.badname": '%1 ist keine Taste, die dieser Rechner hat — drücke stattdessen eine Taste',
 "set.key.nogroup": 'Du bist nicht in der Gruppe `input`, also lässt sich keine einzige Tastatur '
                    'öffnen — die Taste wird direkt vom Gerät gelesen, unterhalb des Desktops',
 "set.key.relogin": 'Du bist in der Gruppe `input`, aber diese Sitzung begann davor — '
                    'melde dich ab und wieder an',
 "set.key.nodevice": 'Keine Tastatur hier meldet %1 — drücke eine andere Taste',
 "set.key.stopped": 'Der Hintergrunddienst läuft nicht, also hört nichts zu',
 "set.key.stale": 'Der Dienst hört noch auf %1 — er hat die Änderung nie übernommen',
 "set.key.off": 'Das Tastenkürzel ist abgeschaltet',
 "set.key.fix.restart": 'Neu starten',
 "set.key.fix.group": 'Mich zu `input` hinzufügen',
 "set.hotkeynote": "Direkt von evdev gelesen, unterhalb von xkb, damit die Taste "
                   "physisch dort bleibt, wo sie ist, auch wenn dein Layout sie "
                   "umbelegt. Ein Modifier lässt sich in Hyprland nicht binden: ihn zu "
                   "drücken ändert die Modmask, was die Release-Bindung sofort auslöst "
                   "und eine Aufnahme von 0,0 s ergibt.",
 "set.audio": "AUDIO",
 "set.preroll": "Vorlauf",
 "set.prerollwhy": "Audio von vor dem Tastendruck. Verkleinere es, und die erste Silbe "
                   "fehlt zunehmend, während PipeWire den Stream öffnet.",
 "set.tail": "Nachlauf",
 "set.warnbelow": "warnen unter",
 "set.maxtake": "max. Aufnahme",
 "set.hud": "HUD",
 "set.keepup": "Ergebnis stehen lassen",
 "set.hudnote": "„changed“ ist die Vorgabe: eine Standzeit, die du immer bezahlst, wird "
                "zum Rauschen, sobald du zwei Sätze hintereinander diktierst — aber eine "
                "stille Korrektur, die du nie gesehen hast, ist schlimmer.",
 "set.notifications": "Benachrichtigungen",
 "set.on": "ein",
 "set.off": "aus",
 "set.history": "VERLAUF",
 "set.keepaudio": "Audio behalten für",
 "set.takes": " Aufnahmen",
 "set.historynote": "Gespeichertes Audio macht es möglich, eine Aufnahme mit einem "
                    "anderen Modell zu wiederholen und den Namens-Probelauf zu fahren. "
                    "Auf 0 gesetzt, verschwindet beides mit.",
 "set.privacy": "WOHIN DEINE STIMME GEHT",
 "set.neverleaves": "Audio verlässt diesen Rechner nie",
 "set.privacynote": "Die Spracherkennung läuft in jedem Modus auf der lokalen GPU. Ein "
                    "Modus, dessen LLM-Schritt ein Remote-Modell ist, schickt den "
                    "transkribierten Text hinaus — der Tab Modi zeigt, welche überhaupt "
                    "einen Schritt haben.",
 "set.editconfig": "Konfiguration bearbeiten",
 "set.restart": "Dienst neu starten",
 "set.configpath": "alles hier ist  ~/.config/omavoi/config.toml",
}
