# -*- coding: utf-8 -*-
PACK = {
 "first.title": 'Configurar Omavoi',
 "first.blurb": 'Dos preguntas y un botón. Nada se ejecuta hasta que pulsas, y cada comando se muestra primero.',
 "first.pick.language": 'Idioma de la interfaz',
 "first.pick.model": 'Modelo de voz',
 "first.reuse": 'pesos que otra herramienta ya dejó en esta máquina — se usan donde están, sin descargar nada',
 "first.reuse.label": 'Usar los que hay',
 "first.m.large": 'la opción por defecto; funciona en cualquier GPU mediante Vulkan',
 "first.m.turbo": 'lo más ligero que todavía vale la pena; una quinta parte de la descarga',
 "first.willrun": 'LO QUE SE EJECUTARÁ',
 "first.needspassword": 'pedirá tu contraseña',
 "first.install": 'Instalar',
 "first.retry": 'Reintentar',
 "first.working": '%1 …',
 "first.failed": '%1 falló — mira abajo',
 "first.cancelled": 'se canceló la petición de contraseña, así que no se instaló nada',
 "first.done": 'Listo — mantén tu tecla y habla',
 "first.dbstale": 'Tu base de datos de paquetes tiene %1 días. Instalar cualquier cosa ahora falla con 404: las versiones que lista ya no están en los mirrors. Arch necesita una actualización del sistema antes de instalar paquetes nuevos de todos modos.',
 "first.updatebtn": 'Actualizar paquetes del sistema',
 "first.pacman404": 'La base de datos de paquetes está desactualizada, así que los mirrors ya no tienen las versiones que lista. Actualiza el sistema arriba y vuelve a intentarlo.',
 "first.pick.hotkey": 'Tecla para hablar',
 "first.hotkey.other": 'otra tecla, p. ej. F9',
 "first.hotkey.note": 'Se lee por debajo de tu distribución de teclado y nunca se apropia de ella, así que la tecla sigue haciendo lo que hace siempre — estas cuatro normalmente no hacen nada por sí solas.',
 "first.group.needed": 'Todavía no estás en el grupo input, así que no se puede leer ninguna tecla. El paso de abajo te añade, y surte efecto en tu próximo inicio de sesión — hasta entonces, dicta desde el módulo de la barra.',
 "first.step.hotkey": 'atajo',
 "first.step.packages": 'paquetes del sistema',
 "first.step.daemon": 'el demonio',
 "first.step.language": 'idioma',
 "first.step.weights": 'pesos del modelo',
 "first.step.use": 'seleccionar el modelo',
 "first.step.mode": 'modo por defecto',
 "first.step.service": 'unidad y atajo',
 "up.title": 'ACTUALIZAR',
 "up.behind": '%1 commits nuevos en la rama del plugin',
 "up.current": 'Al día',
 "up.daemon.blind": 'El servicio se instala por separado y no registra de qué commit '
                     'viene, así que esta pantalla no puede decirte si está al día. '
                     'La actualización lo reinstala de todos modos.',
 "up.unknown": 'No se puede saber — el plugin no se instaló desde git',
 "up.dirty": 'El plugin instalado tiene cambios locales, así que no puede avanzar. Reinstálalo: omarchy plugin remove ai.bkblab.omavoi --yes && omarchy plugin add %1 --enable --yes',
 "up.run": 'Actualizar',
 "up.again": 'Volver a comprobar',
 "up.done": 'Actualizado',
 "up.step.plugin": 'el plugin',
 "up.step.daemon": 'el demonio',
 "up.step.restart": 'reiniciar',
 "models.shared": 'Memoria compartida · ',
 "models.sharednote": 'Esta GPU no tiene memoria propia — los pesos son páginas del sistema como cualquier otra, y la barra de arriba es toda la máquina. Mantener los dos residentes sigue siendo el punto, pero aquí pasarse cuesta swap en lugar de un desalojo: el dictado se queda colgado en vez de solo ir más lento, y todo lo demás en la máquina se cuelga con él.',
 "nav.setup": 'Instalación',
 "setup.rootblurb": 'Los pasos de arriba que necesitan root se pueden hacer aquí, con una sola petición de contraseña — polkit trata pacman como auth_admin, así que en dos llamadas te la pide dos veces. Después se reinicia el demonio: recuerda que falta un motor durante toda la vida del proceso, así que instalar solo el binario lo dejaría diciendo que sigue faltando.',
 "setup.rootrun": 'Instalar esto',
 "nav.history": "Historial",
 "nav.modes": "Modos",
 "nav.models": "Modelos",
 "nav.dictionary": "Diccionario",
 "nav.settings": "Ajustes",
 "lang.label": "Idioma",

 "state.ready": "Listo",
 "state.idle": "inactivo",
 "state.recording": "grabando",
 "state.transcribing": "transcribiendo",
 "state.stopped": "demonio detenido",

 "setup.prefix": "instalación ",
 "setup.title": "Faltan dos piezas por instalar",
 "setup.blurb": "Aquí no se ejecuta nada hasta que lo pulses, y cada paso muestra "
                "primero el comando exacto. Omarchy no ejecuta nada desde una carpeta "
                "de plugin a propósito, así que esta pantalla pregunta.",
 "setup.optional": "opcional",
 "setup.copy": "Copiar",
 "setup.run": "Ejecutar",
 "setup.recheck": "Volver a comprobar",
 "setup.hint": "o ejecuta  omavoi setup  en una terminal — los mismos pasos, el mismo orden",

 "hist.problems": 'QUÉ FALLÓ',
 "hist.steps": 'PASOS LLM',
 "hist.fellthrough": 'falló, se conservó el texto anterior',
 "hist.none": "todavía no hay tomas — mantén %1 y habla",
 "hist.yourkey": "tu tecla",
 "hist.dropped": "descartada — ",
 "hist.audio": "audio",
 "hist.level": "nivel",
 "hist.decode": "decodificación",
 "hist.model": "modelo",
 "hist.language": "idioma",
 "hist.mode": "modo",
 "hist.injected": "insertado por",
 "hist.said": "el modelo dijo:  ",
 "hist.post": "POSPROCESADO",
 "hist.segments": "CONFIANZA POR SEGMENTO",
 "hist.copy": "Copiar",
 "hist.play": "Reproducir",

 "modes.wontfit": 'necesita %1 libres',
 "modes.blocked": 'no se cambió — el modelo de este modo no cabe ahora en la VRAM',
 "modes.speechmodel": 'pesos',
 "modes.speechglobal": 'lo que esté cargado',
 "modes.speechonly1": 'Para este motor solo hay un juego de pesos descargado. El resto está en la pestaña Modelos — uno más pequeño vale la pena para los modos donde importa más la velocidad que la precisión.',
 "modes.newllm": 'PESOS DESCARGADOS QUE NADIE NOMBRA TODAVÍA',
 "modes.newname": "nombre del nuevo modo",
 "modes.here": "aquí",
 "modes.fallback": "por defecto",
 "modes.followwin": "El modo sigue a la ventana enfocada",
 "modes.everytake": "Cada toma usa ",
 "modes.longestwins": "Gana la coincidencia más larga de abajo; si nada coincide, se "
                      "vuelve a default.",
 "modes.matchoff": "La coincidencia por ventana está desactivada, así que las listas de "
                   "abajo están configuradas pero inertes. Hay que ajustarla aplicación "
                   "por aplicación antes de que valga la pena.",
 "modes.hiddenauto": 'La coincidencia por ventana está activada pero sus controles '
                     'están ocultos, así que pulsar un modo abajo no cambiará el que '
                     'se usa de verdad. Desactívala con `omavoi mode auto off`.',
 "modes.following": "sigue a la ventana",
 "modes.fixed": "fijo",
 "modes.activehere": "activo en esta ventana",
 "modes.delete": "Eliminar modo",
 "modes.opens": "SE ABRE EN",
 "modes.notinuse": "sin uso mientras el modo esté fijo",
 "modes.nothing": "nada — a este modo solo se llega por su nombre",
 "modes.classph": "clase de ventana, p. ej. thunderbird",
 "modes.add": "Añadir",
 "modes.matchhint": "Se compara con la clase y el título de Hyprland. Gana la coincidencia "
                    "más larga.",
 "modes.s1": "1  VOZ",
 "modes.speechsub": "lo que se le dice al modelo antes de decodificar",
 "modes.language": "idioma",
 "modes.langhint": "en blanco lo detecta en cada toma; un código como en o zh es más "
                   "rápido y más estable",
 "modes.decoderhint": "pista para el decodificador",
 "modes.promptph": "Se le pasa al modelo. Va bien para la jerga que siempre destroza — es "
                   "una pista, no una garantía; la garantía es el diccionario.",
 "modes.s2": "2  REGLAS",
 "modes.rulessub": "determinista · sin latencia",
 "modes.r.hallucinations": "alucinaciones",
 "modes.r.fillers": "muletillas",
 "modes.r.dictionary": "diccionario",
 "modes.r.names": "nombres",
 "modes.r.cjk": "espaciado CJK",
 "modes.keeppunct": "conservar la puntuación final",
 "modes.s3": "3  LLM",
 "modes.llmsub": "opcional · se ejecuta en orden · un fallo conserva el texto recibido",
 "modes.step": "paso ",
 "modes.stepsuffix": "",
 "modes.remove": "Quitar",
 "modes.stepph": "Dile que edite, no que responda.",
 "modes.nostep": "Este modo no tiene pasada de LLM, así que todavía no hay prompt que "
                 "escribir. Añade una abajo y su prompt aparecerá aquí, editable y ya con "
                 "un valor por defecto utilizable.",
 "modes.addstep": "+ añadir un paso",
 "modes.weights": 'Pesos',
 "modes.inherit": 'seguir la configuración (%1)',
 "modes.nollm": "no hay ningún LLM configurado — mira la pestaña Modelos",
 "modes.inject.auto": "auto",
 "modes.inject.clipboard": "portapapeles",
 "modes.langauto": "auto",
 "modes.s4": "4  INSERCIÓN",
 "modes.injecthint": "auto escribe con wtype, salvo en clientes XWayland y aplicaciones "
                     "Electron conocidas, donde pega en su lugar — allí los keycodes "
                     "sintéticos de wtype llegan como dígitos.",

 "models.speech": "VOZ",
 "models.speechsub": "audio → texto · se ejecuta uno",
 "models.e.vulkan": "Local · Vulkan",
 "models.e.vulkan.sub": "whisper.cpp · pesos ggml · NVIDIA, AMD e Intel por igual",
 "models.e.vulkan.note": "~10 MB de paquetes",
 "models.e.cuda": "Local · CUDA",
 "models.e.cuda.sub": "faster-whisper · pesos ct2 · solo NVIDIA",
 "models.e.cuda.note": "~2,2 GB de wheels",
 "models.e.api": "API remota",
 "models.e.api.sub": "compatible con OpenAI · OpenAI, Groq, SiliconFlow, un servidor local",
 "models.e.api.note": "el audio sale de esta máquina",
 "models.llmcathint": 'lo nombra un paso de un modo, no es un cambio global',
 "models.now": "EN EJECUCIÓN",
 "models.running": "en ejecución",
 "models.notloaded": "sin cargar",
 "models.llmnone": 'ninguno cargado — cada uno arranca en su primer uso',
 "models.coldshort": 'en frío',
 "models.cold": "en frío · arranca al primer uso",
 "models.ready": "listo",
 "models.nodaemon": "no se alcanza el demonio — no se sabe qué está cargado",
 "models.col.name": 'ENTRADA',
 "models.col.model": 'MODELO',
 "models.col.engine": 'MOTOR',
 "models.col.state": 'ESTADO',
 "models.col.usedby": 'USADO POR',
 "models.f.edit": 'Editar',
 "models.f.close": 'Cerrar',
 "models.f.url": 'URL',
 "models.f.model": 'Modelo',
 "models.f.key": 'Clave',
 "models.f.key.place": 'pégala aquí — va a secrets.toml, nunca a la configuración',
 "models.f.key.save": 'Guardar',
 "models.f.key.saved": 'guardada en secrets.toml, 0600',
 "models.f.key.failed": 'no se pudo guardar',
 "models.f.test": 'Probar',
 "models.f.testing": 'pidiendo sus modelos al endpoint…',
 "models.f.testok": 'respondió, %1 modelos — elige uno abajo',
 "models.k.agent": 'Agente del sistema',
 "models.k.agent.sub": 'el agente de código al que está configurado Omarchy — ya con sesión, sin clave, segundos de arranque por toma',
 "models.k.local": 'Modelo local',
 "models.k.local.sub": 'llama.cpp, arrancado y gestionado aquí; un paso puede nombrar sus propios pesos del catálogo de abajo',
 "models.k.api": 'API remota',
 "models.k.api.sub": 'compatible con OpenAI, y la única que envía tus palabras fuera de la máquina — define base_url y una clave',
 "models.k.unset": 'sin configurar',
 "models.stale": "El demonio sigue ejecutando con lo que arrancó",
 "models.loaded": "cargado ",
 "models.configured": "configurado ",
 "models.restart": "Reiniciar el demonio",
 "models.list": "MODELOS · ",
 "models.formathint": "el formato que ejecuta este motor",
 "models.ondisk": "ya está en disco",
 "models.downloading": "descargando…",
 "models.download": "Descargar",
 "models.use": "Usar",
 "models.remove": "Eliminar",
 "models.ourstore": "nuestro almacén",
 "models.outside": "Los pesos que se encuentran fuera de %1 se usan donde están y nunca "
                   "se borran.",
 "models.llm": "LLM",
 "models.llmsub": "texto → texto · cuantos quieras, los modos los llaman por su nombre",
 "models.remote": "remoto",
 "models.local": "local",
 "models.nokey": "sin clave",
 "models.usedby": "usado por ",
 "models.unused": "ningún modo lo nombra — no cuesta nada hasta que alguno lo haga",
 "models.endpointnote": "Los endpoints viven bajo [llm.<name>] — omavoi config edit. Una "
                        "clave nunca va en la configuración: define su variable de entorno, "
                        "o ponla en secrets.toml.",
 "models.vram": "VRAM · ",
 "models.seg.speech": 'modelo de voz',
 "models.seg.other": 'otros programas',
 "models.seg.free": 'libre',
 "models.vramsub": "en uso en toda la máquina",
 "models.needs": "necesita",
 "models.vramnote": "Mantener los dos residentes es justamente el punto: una cadena que "
                    "carga pesos en cada toma cuesta segundos, no milisegundos. Si te pasas, "
                    "lo que se desaloja es el modelo de voz — el dictado va diez veces más "
                    "lento sin que nada diga por qué.",

 "dict.rules": "reglas",
 "dict.names": "nombres",
 "dict.blurb": "oído → querido. Un prompt de decodificador es una pista que el modelo "
               "puede ignorar; esto es la garantía. Se prueba primero la clave más larga, "
               "así que una más corta contenida en ella nunca se dispara.",
 "dict.shadowed": "nunca se dispara — la tapa ",
 "dict.remove": "Quitar",
 "dict.namesblurb": "Escribe solo la forma correcta. Los nombres se meten en el prompt del "
                    "decodificador para que el modelo los produzca, y luego se emparejan "
                    "por sonido para que los homófonos vuelvan al sitio. El emparejamiento "
                    "sigue desactivado hasta que se haya mirado una prueba en seco — es lo "
                    "único aquí que puede estropear texto que ya estaba bien.",
 "dict.matching": "emparejando",
 "dict.seedonly": "solo prompt",
 "dict.dryrun": "Prueba en seco",
 "dict.enable": "Activar emparejamiento",
 "dict.prompt": "prompt: ",
 "dict.none": "(ninguno)",
 "dict.addrule": "Añade una con  omavoi dict add <oído> <querido>",
 "dict.addnames": "Añade varios de golpe con  omavoi names add <nombre> <nombre> …",

 "set.ptt": "mantener para hablar",
 "set.toggle": "alternar",
 "set.dwell.always": "siempre",
 "set.dwell.changed": "si cambió",
 "set.dwell.never": "nunca",
 "set.hotkey": "ATAJO",
 "set.key.rebind": 'Pulsa una tecla',
 "set.key.press": 'esperando — púlsala ahora',
 "set.key": "tecla",
 "set.behaviour": "comportamiento",
 "set.key.check": 'Comprobar de nuevo',
 "set.key.ok": 'escuchando en %1',
 "set.key.testing": 'comprobando…',
 "set.key.badname": '%1 no es una tecla que tenga esta máquina — pulsa una tecla en su lugar',
 "set.key.nogroup": 'No estás en el grupo `input`, así que no se puede abrir ni un teclado — '
                    'la tecla se lee directamente del dispositivo, por debajo del escritorio',
 "set.key.relogin": 'Estás en el grupo `input`, pero esta sesión empezó antes — '
                    'cierra la sesión y vuelve a entrar',
 "set.key.nodevice": 'Ningún teclado aquí informa de %1 — pulsa otra tecla',
 "set.key.stopped": 'El servicio en segundo plano no está corriendo, así que nada escucha',
 "set.key.stale": 'El servicio sigue escuchando en %1 — nunca recogió el cambio',
 "set.key.off": 'El atajo está desactivado',
 "set.key.fix.restart": 'Reiniciarlo',
 "set.key.fix.group": 'Añadirme a `input`',
 "set.hotkeynote": "Se lee desde evdev, por debajo de xkb, así que la tecla se queda donde "
                   "está físicamente aunque tu distribución la remapee. No se puede asignar "
                   "un modificador en Hyprland en su lugar: pulsarlo cambia el modmask, lo "
                   "que dispara al instante el atajo de suelta y graba una toma de 0,0 s.",
 "set.audio": "AUDIO",
 "set.preroll": "pre-grabación",
 "set.prerollwhy": "Audio guardado de antes de pulsar la tecla. Bájalo y la primera sílaba "
                   "empieza a perderse mientras PipeWire abre el flujo.",
 "set.tail": "cola",
 "set.warnbelow": "avisar por debajo de",
 "set.maxtake": "toma máxima",
 "set.hud": "HUD",
 "set.keepup": "mantener el resultado visible",
 "set.hudnote": "«changed» es el valor por defecto: una espera que pagas siempre se "
                "convierte en ruido en cuanto dictas dos frases seguidas, pero una "
                "corrección silenciosa que nunca viste es peor.",
 "set.notifications": "notificaciones",
 "set.on": "activado",
 "set.off": "desactivado",
 "set.history": "HISTORIAL",
 "set.keepaudio": "guardar audio de",
 "set.takes": " tomas",
 "set.historynote": "El audio guardado es lo que permite volver a pasar una toma por otro "
                    "modelo, y la prueba en seco de los nombres. Ponlo a 0 y ambas cosas se "
                    "van con él.",
 "set.privacy": "ADÓNDE VA TU VOZ",
 "set.neverleaves": "El audio nunca sale de esta máquina",
 "set.privacynote": "El reconocimiento de voz corre en la GPU local en todos los modos. Un "
                    "modo cuyo paso de LLM sea un modelo remoto sí envía fuera el texto "
                    "transcrito — la pestaña Modos muestra cuáles tienen algún paso.",
 "set.editconfig": "Editar la configuración",
 "set.restart": "Reiniciar el demonio",
 "set.configpath": "todo esto está en  ~/.config/omavoi/config.toml",
}
