# -*- coding: utf-8 -*-
PACK = {
 "first.title": 'Configurer Omavoi',
 "first.blurb": "Deux questions, puis un bouton. Rien ne s'exécute avant que tu ne presses, et chaque commande est montrée d'abord.",
 "first.pick.language": "Langue de l'interface",
 "first.pick.model": 'Modèle de parole',
 "first.reuse": "des poids qu'un autre outil a déjà posés ici — utilisés là où ils sont, rien à télécharger",
 "first.reuse.label": "Utiliser l'existant",
 "first.m.large": "le choix par défaut ; tourne sur n'importe quel GPU via Vulkan",
 "first.m.turbo": 'le plus léger qui vaille encore la peine ; un cinquième du téléchargement',
 "first.willrun": "CE QUI VA S'EXÉCUTER",
 "first.needspassword": 'demande ton mot de passe',
 "first.install": 'Installer',
 "first.retry": 'Réessayer',
 "first.working": '%1 …',
 "first.failed": '%1 a échoué — voir ci-dessous',
 "first.cancelled": "la demande de mot de passe a été annulée, rien n'a été installé",
 "first.done": 'Prêt — maintiens ta touche et parle',
 "first.dbstale": "Ta base de paquets a %1 jours. Installer quoi que ce soit échoue maintenant en 404 : les versions qu'elle indique ne sont plus sur les miroirs. Arch demande de toute façon une mise à jour du système avant d'ajouter des paquets.",
 "first.updatebtn": 'Mettre à jour les paquets système',
 "first.pacman404": "La base de paquets est périmée, les miroirs n'ont plus les versions qu'elle indique. Mets le système à jour ci-dessus, puis réessaie.",
 "first.pick.hotkey": 'Touche pour parler',
 "first.hotkey.other": 'une autre touche, p. ex. F9',
 "first.hotkey.note": "Lue sous ta disposition de clavier et jamais accaparée : la touche continue de faire ce qu'elle fait d'habitude — ces quatre-là ne font normalement rien seules.",
 "first.group.needed": "Tu n'es pas encore dans le groupe input, donc aucune touche ne peut être lue. L'étape ci-dessous s'en charge, et cela prend effet à ta prochaine connexion — d'ici là, dicte depuis le module de la barre.",
 "first.step.hotkey": 'raccourci',
 "first.step.packages": 'paquets système',
 "first.step.daemon": 'le démon',
 "first.step.language": 'langue',
 "first.step.weights": 'poids du modèle',
 "first.step.use": 'sélectionner le modèle',
 "first.step.mode": 'mode par défaut',
 "first.step.service": 'unité et raccourci',
 "up.title": 'MISE À JOUR',
 "up.behind": '%1 nouveaux commits sur la branche du plugin',
 "up.current": 'À jour',
 "up.daemon.blind": "Le service est installé séparément et ne retient pas de quel "
                     "commit il vient : cet écran ne peut donc pas dire s'il est à jour. "
                     "La mise à jour le réinstalle dans tous les cas.",
 "up.unknown": "Impossible de savoir — le plugin n'a pas été installé depuis git",
 "up.dirty": 'Le plugin installé a des modifications locales, il ne peut pas avancer. Réinstalle-le : omarchy plugin remove ai.bkblab.omavoi --yes && omarchy plugin add %1 --enable --yes',
 "up.run": 'Mettre à jour',
 "up.again": 'Revérifier',
 "up.done": 'Mis à jour',
 "up.step.plugin": 'le plugin',
 "up.step.daemon": 'le démon',
 "up.step.restart": 'redémarrer',
 "models.shared": 'Mémoire partagée · ',
 "models.sharednote": "Ce GPU n'a pas de mémoire propre — les poids sont des pages système ordinaires, et la barre ci-dessus représente toute la machine. Garder les deux en mémoire reste tout l'intérêt, mais ici le surengagement coûte du swap plutôt qu'une éviction : la dictée se bloque au lieu de seulement ralentir, et tout le reste de la machine se bloque avec elle.",
 "nav.setup": 'Installation',
 "setup.rootblurb": "Les étapes ci-dessus qui demandent root peuvent être faites ici, en une seule demande de mot de passe — polkit traite pacman comme auth_admin, donc deux appels signifient deux demandes. Le démon est ensuite redémarré : il retient l'absence d'un moteur pour toute la durée du processus, installer le binaire seul le laisserait continuer à dire qu'il manque.",
 "setup.rootrun": 'Tout installer',
 "nav.history": "Historique",
 "nav.modes": "Modes",
 "nav.models": "Modèles",
 "nav.dictionary": "Dictionnaire",
 "nav.settings": "Réglages",
 "lang.label": "Langue",

 "state.ready": "Prêt",
 "state.idle": "au repos",
 "state.recording": "enregistrement",
 "state.transcribing": "transcription",
 "state.stopped": "démon arrêté",

 "setup.prefix": "installation ",
 "setup.title": "Encore deux éléments à installer",
 "setup.blurb": "Rien ne s'exécute ici avant que tu ne l'actionnes, et chaque étape "
                "montre d'abord la commande exacte. Omarchy n'exécute délibérément "
                "rien depuis un dossier de plugin, donc cet écran demande.",
 "setup.optional": "facultatif",
 "setup.copy": "Copier",
 "setup.run": "Exécuter",
 "setup.recheck": "Revérifier",
 "setup.hint": "ou lance  omavoi setup  dans un terminal — mêmes étapes, même ordre",

 "hist.problems": 'CE QUI A ÉCHOUÉ',
 "hist.steps": 'ÉTAPES LLM',
 "hist.fellthrough": 'a échoué, le texte précédent a été conservé',
 "hist.none": "aucune prise pour l'instant — maintiens %1 et parle",
 "hist.yourkey": "ta touche",
 "hist.dropped": "rejetée — ",
 "hist.audio": "audio",
 "hist.level": "niveau",
 "hist.decode": "décodage",
 "hist.model": "modèle",
 "hist.language": "langue",
 "hist.mode": "mode",
 "hist.injected": "inséré via",
 "hist.said": "le modèle a dit :  ",
 "hist.post": "POST-TRAITEMENT",
 "hist.segments": "CONFIANCE PAR SEGMENT",
 "hist.copy": "Copier",
 "hist.play": "Écouter",

 "modes.wontfit": 'demande %1 de libre',
 "modes.blocked": 'non basculé — le modèle de ce mode ne tient pas dans la VRAM actuellement',
 "modes.speechmodel": 'poids',
 "modes.speechglobal": 'ce qui est chargé',
 "modes.speechonly1": "Un seul jeu de poids est téléchargé pour ce moteur. Les autres sont dans l'onglet Modèles — un plus petit vaut la peine pour les modes où la vitesse compte plus que la précision.",
 "modes.newllm": 'POIDS TÉLÉCHARGÉS QUE RIEN NE NOMME ENCORE',
 "modes.newname": "nom du nouveau mode",
 "modes.here": "ici",
 "modes.fallback": "par défaut",
 "modes.followwin": "Le mode suit la fenêtre active",
 "modes.everytake": "Chaque prise utilise ",
 "modes.longestwins": "La correspondance la plus longue ci-dessous gagne ; sans "
                      "correspondance, retour à default.",
 "modes.matchoff": "La correspondance de fenêtre est désactivée : les listes ci-dessous "
                   "sont configurées mais inertes. Il faut l'ajuster application par "
                   "application avant qu'elle ne soit rentable.",
 "modes.hiddenauto": "La correspondance de fenêtre est activée mais ses commandes sont "
                     "masquées : cliquer sur un mode ci-dessous ne changera pas celui "
                     "qui sert réellement. Désactive-la avec `omavoi mode auto off`.",
 "modes.following": "suit la fenêtre",
 "modes.fixed": "fixe",
 "modes.activehere": "actif dans cette fenêtre",
 "modes.delete": "Supprimer le mode",
 "modes.opens": "S'OUVRE SUR",
 "modes.notinuse": "inutilisé tant que le mode est fixe",
 "modes.nothing": "rien — ce mode ne s'atteint que par son nom",
 "modes.classph": "classe de fenêtre, p. ex. thunderbird",
 "modes.add": "Ajouter",
 "modes.matchhint": "Comparé à la classe et au titre Hyprland. La correspondance la plus "
                    "longue gagne.",
 "modes.s1": "1  PAROLE",
 "modes.speechsub": "ce que le modèle apprend avant de décoder",
 "modes.language": "langue",
 "modes.langhint": "vide la détecte à chaque prise ; un code comme en ou zh est plus "
                   "rapide et plus stable",
 "modes.decoderhint": "indice au décodeur",
 "modes.promptph": "Transmis au modèle. Utile pour le jargon qu'il déforme toujours — un "
                   "indice, pas une garantie ; la garantie, c'est le dictionnaire.",
 "modes.s2": "2  RÈGLES",
 "modes.rulessub": "déterministe · sans latence",
 "modes.r.hallucinations": "hallucinations",
 "modes.r.fillers": "mots de remplissage",
 "modes.r.dictionary": "dictionnaire",
 "modes.r.names": "noms",
 "modes.r.cjk": "espacement CJK",
 "modes.keeppunct": "garder la ponctuation finale",
 "modes.s3": "3  LLM",
 "modes.llmsub": "facultatif · exécuté dans l'ordre · un échec conserve le texte reçu",
 "modes.step": "étape ",
 "modes.stepsuffix": "",
 "modes.remove": "Retirer",
 "modes.stepph": "Dis-lui de corriger, pas de répondre.",
 "modes.nostep": "Ce mode n'a aucune passe LLM, il n'y a donc pas encore de prompt à "
                 "écrire. Ajoutes-en une ci-dessous et son prompt apparaîtra ici, "
                 "modifiable, avec une valeur par défaut utilisable.",
 "modes.addstep": "+ ajouter une étape",
 "modes.weights": 'Poids',
 "modes.inherit": 'suivre la configuration (%1)',
 "modes.nollm": "aucun LLM configuré — voir l'onglet Modèles",
 "modes.inject.auto": "auto",
 "modes.inject.clipboard": "presse-papiers",
 "modes.langauto": "auto",
 "modes.s4": "4  INSERTION",
 "modes.injecthint": "auto tape avec wtype, sauf dans les clients XWayland et les "
                     "applications Electron connues, où il colle à la place — les "
                     "keycodes synthétiques de wtype y arrivent sous forme de chiffres.",

 "models.speech": "PAROLE",
 "models.speechsub": "audio → texte · un seul tourne",
 "models.e.vulkan": "Local · Vulkan",
 "models.e.vulkan.sub": "whisper.cpp · poids ggml · NVIDIA, AMD et Intel indifféremment",
 "models.e.vulkan.note": "~10 Mo de paquets",
 "models.e.cuda": "Local · CUDA",
 "models.e.cuda.sub": "faster-whisper · poids ct2 · NVIDIA uniquement",
 "models.e.cuda.note": "~2,2 Go de wheels",
 "models.e.api": "API distante",
 "models.e.api.sub": "compatible OpenAI · OpenAI, Groq, SiliconFlow, un serveur local",
 "models.e.api.note": "l'audio quitte cette machine",
 "models.llmcathint": 'nommé par une étape de mode, pas un basculement global',
 "models.now": "EN COURS",
 "models.running": "en cours",
 "models.notloaded": "non chargé",
 "models.llmnone": "aucun chargé — chacun démarre à sa première utilisation",
 "models.coldshort": 'à froid',
 "models.cold": "à froid · démarre à la première utilisation",
 "models.ready": "prêt",
 "models.nodaemon": "démon injoignable — impossible de savoir ce qui est chargé",
 "models.col.name": 'ENTRÉE',
 "models.col.model": 'MODÈLE',
 "models.col.engine": 'MOTEUR',
 "models.col.state": 'ÉTAT',
 "models.col.usedby": 'UTILISÉ PAR',
 "models.f.edit": 'Modifier',
 "models.f.close": 'Fermer',
 "models.f.url": 'URL',
 "models.f.model": 'Modèle',
 "models.f.key": 'Clé',
 "models.f.key.place": 'colle-la ici — elle va dans secrets.toml, jamais dans la configuration',
 "models.f.key.save": 'Enregistrer',
 "models.f.key.saved": 'enregistrée dans secrets.toml, 0600',
 "models.f.key.failed": "n'a pas pu être enregistrée",
 "models.f.test": 'Tester',
 "models.f.testing": "on demande ses modèles au point d'accès…",
 "models.f.testok": 'a répondu, %1 modèles — choisis-en un ci-dessous',
 "models.f.key.have": 'une clé est enregistrée',
 "models.f.testfail": "pas de réponse",
 "models.speechapi": 'POINT DE TERMINAISON VOCAL DISTANT',
 "models.speechapi.sub": "L'audio quitte cette machine. À sélectionner ci-dessus sous « API distante ».",
 "models.speechapi.cat": "La liste ci-dessous est celle des poids du moteur local ; "
                         "elle ne sert pas quand le moteur distant est sélectionné.",
 "models.k.agent": 'Agent système',
 "models.k.agent.sub": "l'agent de code auquel Omarchy est réglé — déjà connecté, sans clé, quelques secondes de démarrage par prise",
 "models.k.local": 'Modèle local',
 "models.k.local.sub": 'llama.cpp, lancé et géré ici ; une étape peut nommer ses propres poids dans le catalogue ci-dessous',
 "models.k.api": 'API distante',
 "models.k.api.sub": 'compatible OpenAI, et la seule qui envoie tes mots hors de la machine — définis base_url et une clé',
 "models.k.unset": 'non configuré',
 "models.stale": "Le démon tourne toujours avec ce qu'il a chargé au démarrage",
 "models.loaded": "chargé ",
 "models.configured": "configuré ",
 "models.restart": "Redémarrer le démon",
 "models.list": "MODÈLES · ",
 "models.formathint": "le format que ce moteur exécute",
 "models.ondisk": "déjà sur le disque",
 "models.downloading": "téléchargement…",
 "models.download": "Télécharger",
 "models.use": "Utiliser",
 "models.remove": "Supprimer",
 "models.ourstore": "notre dépôt",
 "models.outside": "Les poids trouvés hors de %1 sont utilisés là où ils sont et jamais "
                   "supprimés.",
 "models.llm": "LLM",
 "models.llmsub": "texte → texte · autant qu'on veut, appelés par leur nom depuis les modes",
 "models.remote": "distant",
 "models.local": "local",
 "models.nokey": "pas de clé",
 "models.usedby": "utilisé par ",
 "models.unused": "nommé par aucun mode — ne coûte rien tant que ce n'est pas le cas",
 "models.endpointnote": "Les points d'accès vivent sous [llm.<name>] — omavoi config edit. "
                        "Une clé ne va jamais dans la configuration : définis sa variable "
                        "d'environnement, ou mets-la dans secrets.toml.",
 "models.vram": "VRAM · ",
 "models.seg.speech": 'modèle de parole',
 "models.seg.other": 'autres programmes',
 "models.seg.free": 'libre',
 "models.vramsub": "utilisée sur toute la machine",
 "models.needs": "requiert",
 "models.vramnote": "Garder les deux en mémoire est tout l'intérêt : une chaîne qui charge "
                    "les poids à chaque prise coûte des secondes, pas des millisecondes. "
                    "En surengagement, c'est le modèle de parole qui est évincé — la dictée "
                    "devient dix fois plus lente sans que rien n'en dise la raison.",

 "dict.rules": "règles",
 "dict.names": "noms",
 "dict.blurb": "entendu → voulu. Un prompt de décodeur est un indice que le modèle peut "
               "ignorer ; ici, c'est la garantie. La clé la plus longue est essayée "
               "d'abord, donc une plus courte qu'elle contient ne se déclenche jamais.",
 "dict.shadowed": "ne se déclenche jamais — masquée par ",
 "dict.remove": "Retirer",
 "dict.namesblurb": "N'écris que la forme correcte. Les noms sont injectés dans le prompt "
                    "du décodeur pour que le modèle les produise, puis appariés par le son "
                    "pour que les homophones se rabattent dessus. L'appariement reste "
                    "désactivé jusqu'à ce qu'un essai à blanc ait été examiné — c'est la "
                    "seule chose ici qui puisse abîmer un texte déjà correct.",
 "dict.matching": "appariement",
 "dict.seedonly": "prompt seulement",
 "dict.dryrun": "Essai à blanc",
 "dict.enable": "Activer l'appariement",
 "dict.prompt": "prompt : ",
 "dict.none": "(aucun)",
 "dict.addrule": "Ajoutes-en une avec  omavoi dict add <entendu> <voulu>",
 "dict.addnames": "Ajoutes-en plusieurs d'un coup avec  omavoi names add <nom> <nom> …",

 "set.ptt": "maintenir pour parler",
 "set.toggle": "bascule",
 "set.dwell.always": "toujours",
 "set.dwell.changed": "si modifié",
 "set.dwell.never": "jamais",
 "set.hotkey": "RACCOURCI",
 "set.key.rebind": 'Appuie sur une touche',
 "set.key.press": 'en attente — appuie maintenant',
 "set.key": "touche",
 "set.behaviour": "comportement",
 "set.key.check": 'Vérifier à nouveau',
 "set.key.ok": 'écoute sur %1',
 "set.key.testing": 'vérification…',
 "set.key.badname": "%1 n'est pas une touche que cette machine possède — appuie plutôt sur une touche",
 "set.key.nogroup": "Tu n'es pas dans le groupe `input`, donc aucun clavier ne peut être ouvert — "
                    "la touche est lue directement sur le périphérique, sous le bureau",
 "set.key.relogin": 'Tu es dans le groupe `input`, mais cette session a commencé avant — '
                    'déconnecte-toi et reconnecte-toi',
 "set.key.nodevice": 'Aucun clavier ici ne signale %1 — appuie sur une autre touche',
 "set.key.stopped": "Le service en arrière-plan ne tourne pas, donc rien n'écoute",
 "set.key.stale": "Le service écoute encore sur %1 — il n'a jamais pris en compte le changement",
 "set.key.off": 'Le raccourci est désactivé',
 "set.key.fix.restart": 'Le redémarrer',
 "set.key.fix.group": "M'ajouter à `input`",
 "set.hotkeynote": "Lue depuis evdev, sous xkb, pour que la touche reste là où elle est "
                   "physiquement même si ta disposition la remappe. Impossible d'associer "
                   "un modificateur dans Hyprland à la place : appuyer dessus change le "
                   "modmask, ce qui déclenche aussitôt le raccourci de relâchement et "
                   "enregistre une prise de 0,0 s.",
 "set.audio": "AUDIO",
 "set.preroll": "pré-enregistrement",
 "set.prerollwhy": "Audio conservé d'avant l'appui sur la touche. Réduis-le et la première "
                   "syllabe commence à manquer pendant que PipeWire ouvre le flux.",
 "set.tail": "traîne",
 "set.warnbelow": "alerter en dessous de",
 "set.maxtake": "prise max",
 "set.hud": "HUD",
 "set.keepup": "laisser le résultat affiché",
 "set.hudnote": "« changed » est la valeur par défaut : une temporisation que tu paies "
                "toujours devient du bruit dès que tu dictes deux phrases de suite, mais "
                "une correction silencieuse que tu n'as jamais vue est pire.",
 "set.notifications": "notifications",
 "set.on": "activé",
 "set.off": "désactivé",
 "set.history": "HISTORIQUE",
 "set.keepaudio": "garder l'audio pour",
 "set.takes": " prises",
 "set.historynote": "L'audio stocké est ce qui rend possible de rejouer une prise sur un "
                    "autre modèle, et l'essai à blanc des noms. Mets-le à 0 et les deux "
                    "disparaissent avec.",
 "set.privacy": "OÙ VA TA VOIX",
 "set.neverleaves": "L'audio ne quitte jamais cette machine",
 "set.privacynote": "La reconnaissance vocale tourne sur le GPU local dans tous les modes. "
                    "Un mode dont l'étape LLM est un modèle distant, lui, envoie le texte "
                    "transcrit dehors — l'onglet Modes montre lesquels ont une étape.",
 "set.editconfig": "Modifier la configuration",
 "set.restart": "Redémarrer le démon",
 "set.configpath": "tout ici est  ~/.config/omavoi/config.toml",
}
