# -*- coding: utf-8 -*-
PACK = {
 "first.title": 'Omavoi のセットアップ',
 "first.blurb": '質問は二つ、そのあとボタン一つ。押すまで何も実行されず、コマンドは必ず先に表示します。',
 "first.pick.language": '画面の言語',
 "first.pick.model": '音声モデル',
 "first.reuse": '他のツールがこの端末に既に置いた重み —— その場所のまま使い、ダウンロードは不要です',
 "first.reuse.label": '既にあるものを使う',
 "first.m.large": '既定の選択。Vulkan 経由でどの GPU でも動きます',
 "first.m.turbo": 'まだ使う価値のある最も軽いもの。ダウンロードは五分の一です',
 "first.willrun": '実行される内容',
 "first.needspassword": 'パスワードを尋ねます',
 "first.install": 'インストール',
 "first.retry": '再試行',
 "first.working": '%1 …',
 "first.failed": '%1 に失敗しました —— 下を参照してください',
 "first.cancelled": 'パスワード入力が取り消されたので、何もインストールされていません',
 "first.done": '準備完了 —— キーを押しながら話してください',
 "first.dbstale": 'パッケージデータベースが %1 日前のものです。この状態で何かをインストールすると 404 で失敗します —— そこに記録されたバージョンはもうミラーにありません。Arch では新しいパッケージを入れる前にシステム更新が必要です。',
 "first.updatebtn": 'システムパッケージを更新',
 "first.pacman404": 'パッケージデータベースが古く、記録されたバージョンがミラーに残っていません。上でシステムを更新してから、もう一度お試しください。',
 "first.pick.hotkey": '押しながら話すキー',
 "first.hotkey.other": '他のキー（例：F9）',
 "first.hotkey.note": 'キーボード配列より下で読み取り、キーを奪うことはないので、そのキーは本来の動作をそのまま続けます —— 上の四つは単独で押しても普通は何も起きません。',
 "first.group.needed": 'まだ input グループに入っていないため、どのキーも読み取れません。下のステップで追加しますが、有効になるのは次回ログイン時です —— それまではバーのモジュールから音声入力できます。',
 "first.step.hotkey": 'ホットキー',
 "first.step.packages": 'システムパッケージ',
 "first.step.daemon": 'デーモン',
 "first.step.language": '言語',
 "first.step.weights": 'モデルの重み',
 "first.step.use": 'モデルを選択',
 "first.step.mode": '既定のモード',
 "first.step.service": 'ユニットとキー割り当て',
 "up.title": '更新',
 "up.behind": 'プラグインのブランチに %1 件の新しいコミットがあります',
 "up.current": '最新です',
 "up.unknown": '判定できません —— このプラグインは git から入れたものではありません',
 "up.dirty": 'インストール済みのプラグインにローカルの変更があるため早送りできません。入れ直してください: omarchy plugin remove ai.bkblab.omavoi --yes && omarchy plugin add %1 --enable --yes',
 "up.run": '更新する',
 "up.again": 'もう一度確認',
 "up.done": '更新しました',
 "up.step.plugin": 'プラグイン',
 "up.step.daemon": 'デーモン',
 "up.step.restart": '再起動',
 "models.shared": '共有メモリ · ',
 "models.sharednote": 'この GPU に専用メモリはありません —— 重みは通常のシステムメモリ上にあり、上のバーは端末全体を表しています。両方を常駐させることが肝心なのは変わりませんが、ここで詰め込みすぎた代償は追い出しではなく swap です。入力は遅くなるのではなく止まり、端末の他のすべても一緒に止まります。',
 "nav.setup": 'セットアップ',
 "setup.rootblurb": '上の root が必要な手順は、ここでパスワード入力一回で済ませられます —— polkit は pacman を auth_admin として扱うため、二回に分けて呼べば二回聞かれます。その後デーモンを再起動します。エンジンが無いという判断はプロセスが生きている間キャッシュされるので、バイナリを入れるだけでは無いと言い続けます。',
 "setup.rootrun": 'まとめて入れる',
 "nav.history": "履歴",
 "nav.modes": "モード",
 "nav.models": "モデル",
 "nav.dictionary": "辞書",
 "nav.settings": "設定",
 "lang.label": "言語",

 "state.ready": "準備完了",
 "state.idle": "待機中",
 "state.recording": "録音中",
 "state.transcribing": "文字起こし中",
 "state.stopped": "デーモン停止",

 "setup.prefix": "セットアップ ",
 "setup.title": "あと二つインストールが必要です",
 "setup.blurb": "ここでは押すまで何も実行されず、各ステップは実行前に正確なコマンドを表示します。"
                "Omarchy はプラグインフォルダの中身を意図的に一切実行しないので、"
                "この画面が代わりに尋ねます。",
 "setup.optional": "任意",
 "setup.copy": "コピー",
 "setup.run": "実行",
 "setup.recheck": "再確認",
 "setup.hint": "またはターミナルで  omavoi setup  を実行 —— 手順も順序も同じです",

 "hist.problems": '何が失敗したか',
 "hist.steps": 'LLM ステップ',
 "hist.fellthrough": '失敗したため、前のテキストを保持しました',
 "hist.none": "まだ録音がありません —— %1 を押しながら話してください",
 "hist.yourkey": "設定したキー",
 "hist.dropped": "破棄 —— ",
 "hist.audio": "音声",
 "hist.level": "レベル",
 "hist.decode": "デコード",
 "hist.model": "モデル",
 "hist.language": "言語",
 "hist.mode": "モード",
 "hist.injected": "入力方法",
 "hist.said": "モデルの出力：  ",
 "hist.post": "後処理",
 "hist.segments": "セグメント信頼度",
 "hist.copy": "コピー",
 "hist.play": "再生",

 "modes.wontfit": '空き %1 が必要',
 "modes.blocked": '切り替えていません —— このモードのモデルは今の VRAM に収まりません',
 "modes.speechmodel": '重み',
 "modes.speechglobal": '読み込まれているもの',
 "modes.speechonly1": 'このエンジン用にダウンロード済みの重みは一組だけです。残りは「モデル」タブにあります —— 正確さより速さが要るモードには小さいものを用意しておく価値があります。',
 "modes.newllm": 'ダウンロード済みで、まだどこからも呼ばれていない重み',
 "modes.newname": "新しいモード名",
 "modes.here": "現在",
 "modes.fallback": "フォールバック",
 "modes.followwin": "モードはフォーカス中のウィンドウに追従します",
 "modes.everytake": "毎回このモードを使用： ",
 "modes.longestwins": "下で最も長く一致したものが勝ちます。何も一致しなければ default に戻ります。",
 "modes.matchoff": "ウィンドウ照合は無効なので、下のリストは設定済みでも動作しません。"
                   "役に立つまでにはアプリごとの調整が必要です。",
 "modes.following": "ウィンドウに追従",
 "modes.fixed": "固定",
 "modes.activehere": "このウィンドウで有効",
 "modes.delete": "モードを削除",
 "modes.opens": "起動条件",
 "modes.notinuse": "モードが固定の間は使われません",
 "modes.nothing": "なし —— このモードは名前でしか呼び出せません",
 "modes.classph": "ウィンドウクラス（例：thunderbird）",
 "modes.add": "追加",
 "modes.matchhint": "Hyprland のクラスとタイトルに照合します。最も長い一致が勝ちます。",
 "modes.s1": "1  音声",
 "modes.speechsub": "デコード前にモデルへ伝える内容",
 "modes.language": "言語",
 "modes.langhint": "空欄なら毎回自動判定。en や zh のようなコードを指定すると速く安定します",
 "modes.decoderhint": "デコーダーへのヒント",
 "modes.promptph": "モデルに渡されます。いつも崩れる専門用語に有効 —— これはヒントで保証ではありません。"
                   "保証するのは辞書です。",
 "modes.s2": "2  ルール",
 "modes.rulessub": "決定的 · 遅延なし",
 "modes.r.hallucinations": "幻覚除去",
 "modes.r.fillers": "フィラー",
 "modes.r.dictionary": "辞書",
 "modes.r.names": "固有名詞",
 "modes.r.cjk": "CJK 空白",
 "modes.keeppunct": "文末の句読点を残す",
 "modes.s3": "3  LLM",
 "modes.llmsub": "任意 · 順番に実行 · 失敗すると渡されたテキストをそのまま保持",
 "modes.step": "ステップ ",
 "modes.stepsuffix": "",
 "modes.remove": "削除",
 "modes.stepph": "回答ではなく編集をさせる指示を書いてください。",
 "modes.nostep": "このモードには LLM の処理がないので、まだ書くプロンプトがありません。"
                 "下で追加すると、そのプロンプトがここに現れ、編集できます。"
                 "使える初期値が最初から入っています。",
 "modes.addstep": "+ ステップを追加",
 "modes.nollm": "LLM が未設定です —— 「モデル」タブを確認してください",
 "modes.inject.auto": "自動",
 "modes.inject.clipboard": "クリップボード",
 "modes.langauto": "自動",
 "modes.s4": "4  入力",
 "modes.injecthint": "自動では wtype で打鍵しますが、XWayland クライアントと既知の Electron アプリでは"
                     "貼り付けに切り替えます —— wtype の合成キーコードはそれらには数字として届くためです。",

 "models.speech": "音声",
 "models.speechsub": "音声 → テキスト · 動くのは一つだけ",
 "models.e.vulkan": "ローカル · Vulkan",
 "models.e.vulkan.sub": "whisper.cpp · ggml 重み · NVIDIA、AMD、Intel いずれでも",
 "models.e.vulkan.note": "パッケージ約 10 MB",
 "models.e.cuda": "ローカル · CUDA",
 "models.e.cuda.sub": "faster-whisper · ct2 重み · NVIDIA 限定",
 "models.e.cuda.note": "wheel 約 2.2 GB",
 "models.e.api": "リモート API",
 "models.e.api.sub": "OpenAI 互換 · OpenAI、Groq、SiliconFlow、ローカルサーバー",
 "models.e.api.note": "音声がこの端末から出ます",
 "models.llmcathint": 'モードのステップが名前で呼び出します。全体の切り替えではありません',
 "models.now": "稼働中",
 "models.running": "稼働中",
 "models.notloaded": "未ロード",
 "models.cold": "停止中 · 初回利用時に起動",
 "models.ready": "準備完了",
 "models.nodaemon": "デーモンに接続できません —— 何がロードされているか不明です",
 "models.stale": "デーモンは起動時に読み込んだものをまだ使っています",
 "models.loaded": "読み込み済み ",
 "models.configured": "設定済み ",
 "models.restart": "デーモンを再起動",
 "models.list": "モデル · ",
 "models.formathint": "このエンジンが扱う形式",
 "models.ondisk": "ディスクに既にあります",
 "models.downloading": "ダウンロード中…",
 "models.download": "ダウンロード",
 "models.use": "使用",
 "models.remove": "削除",
 "models.ourstore": "こちらの保存先",
 "models.outside": "%1 の外で見つかった重みはその場所のまま使われ、削除されることはありません。",
 "models.llm": "LLM",
 "models.llmsub": "テキスト → テキスト · 数はいくつでも、モードが名前で呼び出します",
 "models.remote": "リモート",
 "models.local": "ローカル",
 "models.nokey": "キーなし",
 "models.usedby": "使用中のモード： ",
 "models.unused": "どのモードからも呼ばれていません —— 呼ばれるまで負荷はゼロです",
 "models.endpointnote": "エンドポイントは [llm.<name>] の下にあります —— omavoi config edit。"
                        "キーは決して設定ファイルに書きません。環境変数に設定するか、"
                        "secrets.toml に置いてください。",
 "models.vram": "VRAM · ",
 "models.seg.speech": '音声モデル',
 "models.seg.other": '他のプログラム',
 "models.seg.free": '空き',
 "models.vramsub": "端末全体での使用量",
 "models.needs": "必要",
 "models.vramnote": "両方を常駐させることが肝心です。録音ごとに重みを読み込む構成では"
                    "ミリ秒ではなく秒単位のコストがかかります。詰め込みすぎると追い出されるのは"
                    "音声モデルの側で —— 理由を告げるものが何もないまま、入力が十倍遅くなります。",

 "dict.rules": "ルール",
 "dict.names": "固有名詞",
 "dict.blurb": "聞こえた語 → 本来の語。デコーダーのプロンプトはモデルが無視できる助言にすぎませんが、"
               "こちらは保証です。照合は最も長いキーから試すので、それに含まれる短いキーは"
               "決して発火しません。",
 "dict.shadowed": "決して発火しません —— 次のキーに隠れています： ",
 "dict.remove": "削除",
 "dict.namesblurb": "正しい表記だけを書いてください。固有名詞はデコーダーのプロンプトに入れて"
                    "モデルがその形を出すようにし、その後で音の近さで照合して同音の表記を"
                    "引き戻します。照合はドライランを確認するまで無効のままです —— "
                    "ここで唯一、すでに正しいテキストを壊しうる機能だからです。",
 "dict.matching": "照合中",
 "dict.seedonly": "プロンプトのみ",
 "dict.dryrun": "ドライラン",
 "dict.enable": "照合を有効化",
 "dict.prompt": "プロンプト： ",
 "dict.none": "（なし）",
 "dict.addrule": "追加するには  omavoi dict add <聞こえた語> <本来の語>",
 "dict.addnames": "まとめて追加するには  omavoi names add <名前> <名前> …",

 "set.ptt": "押している間だけ話す",
 "set.toggle": "押して切り替え",
 "set.dwell.always": "常に",
 "set.dwell.changed": "変化したとき",
 "set.dwell.never": "しない",
 "set.hotkey": "ホットキー",
 "set.key": "キー",
 "set.behaviour": "動作",
 "set.hotkeynote": "xkb より下の evdev から直接読むので、キーボード配列で再割り当てしても"
                   "キーは物理的な位置のままです。代わりに Hyprland で修飾キーを割り当てることは"
                   "できません。修飾キーを押すと modmask が変わり、離したときのバインドが即座に"
                   "発火して 0.0 秒の録音になります。",
 "set.audio": "音声",
 "set.preroll": "先読みバッファ",
 "set.prerollwhy": "キーを押す前の音声を保持します。小さくすると、PipeWire がストリームを開く間に"
                   "最初の音節が欠け始めます。",
 "set.tail": "末尾の余裕",
 "set.warnbelow": "この値未満で警告",
 "set.maxtake": "一回の上限",
 "set.hud": "HUD",
 "set.keepup": "結果を表示したままにする",
 "set.hudnote": "既定は「changed」です。毎回必ず表示を待つ設定は、二文続けて話した瞬間に"
                "邪魔になります。とはいえ、見ないまま静かに書き換えられるほうが厄介です。",
 "set.notifications": "通知",
 "set.on": "オン",
 "set.off": "オフ",
 "set.history": "履歴",
 "set.keepaudio": "音声を保持する件数",
 "set.takes": " 件",
 "set.historynote": "保存した音声があるからこそ、別のモデルで録音を再実行することも、"
                    "固有名詞のドライランもできます。0 にすると、その両方が一緒に失われます。",
 "set.privacy": "あなたの声はどこへ行くか",
 "set.neverleaves": "音声はこの端末から出ません",
 "set.privacynote": "音声認識はどのモードでもローカルの GPU で動きます。ただし LLM ステップに"
                    "リモートモデルを使うモードは、文字起こししたテキストを外へ送ります —— "
                    "どのモードにステップがあるかは「モード」タブで確認できます。",
 "set.editconfig": "設定を編集",
 "set.restart": "デーモンを再起動",
 "set.configpath": "ここのすべては  ~/.config/omavoi/config.toml にあります",
}
