# -*- coding: utf-8 -*-
PACK = {
 "first.title": 'Thiết lập Omavoi',
 "first.blurb": 'Hai câu hỏi, rồi một nút. Không có gì chạy cho đến khi bạn bấm, và mọi câu lệnh đều được hiện ra trước.',
 "first.pick.language": 'Ngôn ngữ giao diện',
 "first.pick.model": 'Mô hình giọng nói',
 "first.reuse": 'trọng số mà một công cụ khác đã để trên máy này — dùng ngay tại chỗ, không cần tải',
 "first.reuse.label": 'Dùng cái đang có',
 "first.m.large": 'mặc định; chạy trên GPU nào cũng được thông qua Vulkan',
 "first.m.turbo": 'thứ nhẹ nhất mà vẫn đáng dùng; chỉ một phần năm dung lượng tải',
 "first.willrun": 'NHỮNG GÌ SẼ CHẠY',
 "first.needspassword": 'sẽ hỏi mật khẩu của bạn',
 "first.install": 'Cài đặt',
 "first.retry": 'Thử lại',
 "first.working": '%1 …',
 "first.failed": '%1 thất bại — xem bên dưới',
 "first.cancelled": 'hộp nhập mật khẩu đã bị hủy, nên chưa có gì được cài',
 "first.done": 'Xong — giữ phím của bạn và nói',
 "first.dbstale": 'Cơ sở dữ liệu gói của bạn đã cũ %1 ngày. Cài bất cứ gì lúc này sẽ lỗi 404: các phiên bản nó ghi không còn trên mirror. Dù sao Arch cũng cần cập nhật hệ thống trước khi thêm gói mới.',
 "first.updatebtn": 'Cập nhật gói hệ thống',
 "first.pacman404": 'Cơ sở dữ liệu gói đã lạc hậu nên mirror không còn các phiên bản nó ghi. Hãy cập nhật hệ thống ở trên rồi thử lại.',
 "first.pick.hotkey": 'Phím giữ để nói',
 "first.hotkey.other": 'phím khác, ví dụ F9',
 "first.hotkey.note": 'Đọc bên dưới bố cục bàn phím và không bao giờ chiếm phím, nên phím vẫn làm đúng việc thường ngày của nó — bốn phím trên khi bấm một mình thường không làm gì.',
 "first.group.needed": 'Bạn chưa thuộc nhóm input, nên không đọc được phím nào. Bước bên dưới sẽ thêm bạn vào, và chỉ có hiệu lực từ lần đăng nhập kế tiếp — trước đó hãy dùng module trên thanh bar.',
 "first.step.hotkey": 'phím tắt',
 "first.step.packages": 'gói hệ thống',
 "first.step.daemon": 'dịch vụ',
 "first.step.language": 'ngôn ngữ',
 "first.step.weights": 'trọng số mô hình',
 "first.step.use": 'chọn mô hình',
 "first.step.mode": 'chế độ mặc định',
 "first.step.service": 'unit và phím tắt',
 "up.title": 'CẬP NHẬT',
 "up.behind": 'có %1 commit mới trên nhánh của plugin',
 "up.current": 'Đã mới nhất',
 "up.daemon.blind": 'Dịch vụ nền được cài riêng và không ghi lại nó đến từ commit nào, '
                     'nên trang này không thể cho bạn biết nó có mới nhất hay không. '
                     'Chạy cập nhật sẽ cài lại nó trong mọi trường hợp.',
 "up.unknown": 'Không xác định được — plugin này không cài từ git',
 "up.dirty": 'Plugin đã cài có thay đổi cục bộ nên không fast-forward được. Hãy cài lại: omarchy plugin remove ai.bkblab.omavoi --yes && omarchy plugin add %1 --enable --yes',
 "up.run": 'Cập nhật',
 "up.again": 'Kiểm tra lại',
 "up.done": 'Đã cập nhật',
 "up.step.plugin": 'plugin',
 "up.step.daemon": 'dịch vụ',
 "up.step.restart": 'khởi động lại',
 "models.shared": 'Bộ nhớ dùng chung · ',
 "models.sharednote": 'GPU này không có bộ nhớ riêng — trọng số nằm trong bộ nhớ hệ thống thông thường, và thanh phía trên là toàn bộ máy. Giữ cả hai thường trú vẫn là điểm chính, nhưng vượt quá ở đây phải trả bằng swap chứ không phải bị đẩy ra: việc nhập bằng giọng sẽ treo hẳn thay vì chỉ chậm đi, và mọi thứ khác trên máy treo theo.',
 "nav.setup": 'Cài đặt',
 "setup.rootblurb": 'Các bước ở trên cần root có thể làm ngay tại đây, chỉ hỏi mật khẩu một lần — polkit xem pacman là auth_admin, gọi hai lần thì bị hỏi hai lần. Sau đó daemon được khởi động lại: nó ghi nhớ việc thiếu engine trong suốt vòng đời tiến trình, nên chỉ cài binary thôi thì nó vẫn báo là thiếu.',
 "setup.rootrun": 'Cài các mục này',
 "nav.history": "Lịch sử",
 "nav.modes": "Chế độ",
 "nav.models": "Mô hình",
 "nav.dictionary": "Từ điển",
 "nav.settings": "Cài đặt",
 "lang.label": "Ngôn ngữ",

 "state.ready": "Sẵn sàng",
 "state.idle": "rảnh",
 "state.recording": "đang ghi",
 "state.transcribing": "đang chuyển thành chữ",
 "state.stopped": "dịch vụ đã dừng",

 "setup.prefix": "cài đặt ",
 "setup.title": "Còn hai phần nữa cần cài",
 "setup.blurb": "Ở đây không có gì chạy cho đến khi bạn bấm, và mỗi bước đều hiện "
                "đúng câu lệnh trước. Omarchy cố tình không chạy bất cứ thứ gì từ "
                "trong thư mục plugin, nên màn hình này phải hỏi bạn.",
 "setup.optional": "không bắt buộc",
 "setup.copy": "Sao chép",
 "setup.run": "Chạy",
 "setup.recheck": "Kiểm tra lại",
 "setup.hint": "hoặc chạy  omavoi setup  trong terminal — cùng các bước, cùng thứ tự",

 "hist.problems": 'ĐÃ SAI Ở ĐÂU',
 "hist.steps": 'CÁC BƯỚC LLM',
 "hist.fellthrough": 'thất bại, giữ lại văn bản trước đó',
 "hist.none": "chưa có bản ghi nào — giữ %1 và nói",
 "hist.yourkey": "phím của bạn",
 "hist.dropped": "đã bỏ — ",
 "hist.audio": "âm thanh",
 "hist.level": "mức",
 "hist.decode": "giải mã",
 "hist.model": "mô hình",
 "hist.language": "ngôn ngữ",
 "hist.mode": "chế độ",
 "hist.injected": "cách chèn",
 "hist.said": "mô hình nghe thành:  ",
 "hist.post": "HẬU XỬ LÝ",
 "hist.segments": "ĐỘ TIN CẬY TỪNG ĐOẠN",
 "hist.copy": "Sao chép",
 "hist.play": "Phát",

 "modes.wontfit": 'cần %1 trống',
 "modes.blocked": 'chưa chuyển — mô hình của chế độ này hiện không vừa VRAM',
 "modes.speechmodel": 'trọng số',
 "modes.speechglobal": 'cái đang được nạp',
 "modes.speechonly1": 'Chỉ có một bộ trọng số đã tải cho engine này. Phần còn lại ở thẻ Mô hình — một bộ nhỏ hơn đáng có cho những chế độ cần nhanh hơn là chính xác.',
 "modes.newllm": 'TRỌNG SỐ ĐÃ TẢI MÀ CHƯA CÓ MỤC NÀO GỌI',
 "modes.newname": "tên chế độ mới",
 "modes.here": "hiện tại",
 "modes.fallback": "dự phòng",
 "modes.followwin": "Chế độ đi theo cửa sổ đang được chọn",
 "modes.everytake": "Mọi bản ghi đều dùng ",
 "modes.longestwins": "Mẫu khớp dài nhất bên dưới thắng; không khớp gì thì quay về default.",
 "modes.matchoff": "Việc khớp theo cửa sổ đang tắt, nên các danh sách bên dưới đã được "
                   "cấu hình nhưng không có tác dụng. Nó cần được tinh chỉnh cho từng "
                   "ứng dụng trước khi đáng dùng.",
 "modes.hiddenauto": 'Khớp theo cửa sổ đang bật nhưng phần điều khiển của nó đã bị ẩn, '
                     'nên bấm một chế độ bên dưới sẽ không thay đổi chế độ thực sự '
                     'được dùng. Tắt nó bằng `omavoi mode auto off`.',
 "modes.following": "đi theo cửa sổ",
 "modes.fixed": "cố định",
 "modes.activehere": "đang dùng trong cửa sổ này",
 "modes.delete": "Xóa chế độ",
 "modes.opens": "MỞ KHI",
 "modes.notinuse": "không dùng khi chế độ đang cố định",
 "modes.nothing": "không có — chế độ này chỉ gọi được bằng tên",
 "modes.classph": "class cửa sổ, ví dụ thunderbird",
 "modes.add": "Thêm",
 "modes.matchhint": "Đối chiếu với class và title của Hyprland. Mẫu khớp dài nhất thắng.",
 "modes.s1": "1  GIỌNG NÓI",
 "modes.speechsub": "những gì mô hình được cho biết trước khi giải mã",
 "modes.language": "ngôn ngữ",
 "modes.langhint": "để trống thì tự nhận mỗi lần; đặt mã như en hay zh sẽ nhanh và ổn định hơn",
 "modes.decoderhint": "gợi ý cho bộ giải mã",
 "modes.promptph": "Được đưa vào mô hình. Hữu ích với thuật ngữ mà nó cứ nghe sai — đây là "
                   "gợi ý, không phải bảo đảm; thứ bảo đảm là từ điển.",
 "modes.s2": "2  QUY TẮC",
 "modes.rulessub": "tất định · không thêm độ trễ",
 "modes.r.hallucinations": "câu bịa",
 "modes.r.fillers": "từ đệm",
 "modes.r.dictionary": "từ điển",
 "modes.r.names": "tên riêng",
 "modes.r.cjk": "khoảng cách CJK",
 "modes.keeppunct": "giữ dấu câu ở cuối",
 "modes.s3": "3  LLM",
 "modes.llmsub": "không bắt buộc · chạy theo thứ tự · nếu lỗi thì giữ nguyên văn bản nhận được",
 "modes.step": "bước ",
 "modes.stepsuffix": "",
 "modes.remove": "Bỏ",
 "modes.stepph": "Hãy bảo nó sửa văn bản, đừng để nó trả lời.",
 "modes.nostep": "Chế độ này không có bước LLM nào, nên chưa có prompt để viết. Thêm một "
                 "bước bên dưới thì prompt của nó sẽ hiện ở đây, sửa được, và đã có sẵn "
                 "một giá trị mặc định dùng được.",
 "modes.addstep": "+ thêm một bước",
 "modes.weights": 'Trọng số',
 "modes.inherit": 'theo cấu hình (%1)',
 "modes.nollm": "chưa cấu hình LLM nào — xem thẻ Mô hình",
 "modes.inject.auto": "tự động",
 "modes.inject.clipboard": "clipboard",
 "modes.langauto": "tự động",
 "modes.s4": "4  CHÈN CHỮ",
 "modes.injecthint": "tự động sẽ gõ bằng wtype, trừ các client XWayland và những ứng dụng "
                     "Electron đã biết, ở đó nó dán thay vì gõ — keycode tổng hợp của "
                     "wtype đến những ứng dụng đó dưới dạng chữ số.",

 "models.speech": "GIỌNG NÓI",
 "models.speechsub": "âm thanh → chữ · chỉ một cái chạy",
 "models.e.vulkan": "Cục bộ · Vulkan",
 "models.e.vulkan.sub": "whisper.cpp · trọng số ggml · NVIDIA, AMD và Intel đều được",
 "models.e.vulkan.note": "khoảng 10 MB gói",
 "models.e.cuda": "Cục bộ · CUDA",
 "models.e.cuda.sub": "faster-whisper · trọng số ct2 · chỉ NVIDIA",
 "models.e.cuda.note": "khoảng 2,2 GB wheel",
 "models.e.api": "API từ xa",
 "models.e.api.sub": "tương thích OpenAI · OpenAI, Groq, SiliconFlow, một server cục bộ",
 "models.e.api.note": "âm thanh sẽ rời khỏi máy này",
 "models.llmcathint": 'được bước của một chế độ gọi theo tên, không phải chuyển toàn cục',
 "models.now": "ĐANG CHẠY",
 "models.running": "đang chạy",
 "models.notloaded": "chưa nạp",
 "models.llmnone": 'chưa nạp — mỗi cái khởi động khi dùng lần đầu',
 "models.coldshort": 'chưa chạy',
 "models.cold": "chưa khởi động · chạy khi dùng lần đầu",
 "models.ready": "sẵn sàng",
 "models.nodaemon": "không liên lạc được dịch vụ — không rõ đang nạp những gì",
 "models.col.name": 'MỤC',
 "models.col.model": 'MÔ HÌNH',
 "models.col.engine": 'ENGINE',
 "models.col.state": 'TRẠNG THÁI',
 "models.col.usedby": 'DÙNG BỞI',
 "models.f.edit": 'Sửa',
 "models.f.close": 'Đóng',
 "models.f.url": 'URL',
 "models.f.model": 'Mô hình',
 "models.f.key": 'Khóa',
 "models.f.key.place": 'dán vào đây — sẽ vào secrets.toml, không bao giờ vào file cấu hình',
 "models.f.key.save": 'Lưu',
 "models.f.key.saved": 'đã lưu vào secrets.toml, 0600',
 "models.f.key.failed": 'không lưu được',
 "models.f.test": 'Kiểm tra',
 "models.f.testing": 'đang hỏi danh sách mô hình từ điểm cuối…',
 "models.f.testok": 'đã trả lời, %1 mô hình — chọn một bên dưới',
 "models.k.agent": 'Agent hệ thống',
 "models.k.agent.sub": 'agent lập trình mà Omarchy đang đặt — đã đăng nhập, không cần khóa, mất vài giây khởi động mỗi lần',
 "models.k.local": 'Mô hình cục bộ',
 "models.k.local.sub": 'llama.cpp, do chương trình này khởi động và quản lý; mỗi bước có thể chọn trọng số riêng từ danh mục bên dưới',
 "models.k.api": 'API từ xa',
 "models.k.api.sub": 'tương thích OpenAI, và là cái duy nhất gửi lời của bạn ra khỏi máy — hãy đặt base_url và khóa',
 "models.k.unset": 'chưa cấu hình',
 "models.stale": "Dịch vụ vẫn đang chạy thứ nó nạp lúc khởi động",
 "models.loaded": "đã nạp ",
 "models.configured": "đã cấu hình ",
 "models.restart": "Khởi động lại dịch vụ",
 "models.list": "MÔ HÌNH · ",
 "models.formathint": "định dạng mà engine này chạy",
 "models.ondisk": "đã có trên đĩa",
 "models.downloading": "đang tải…",
 "models.download": "Tải về",
 "models.use": "Dùng",
 "models.remove": "Xóa",
 "models.ourstore": "kho của chúng ta",
 "models.outside": "Trọng số tìm thấy ngoài %1 sẽ được dùng ngay tại chỗ và không bao giờ bị xóa.",
 "models.llm": "LLM",
 "models.llmsub": "chữ → chữ · bao nhiêu cũng được, các chế độ gọi theo tên",
 "models.remote": "từ xa",
 "models.local": "cục bộ",
 "models.nokey": "chưa có khóa",
 "models.usedby": "được dùng bởi ",
 "models.unused": "chưa chế độ nào gọi tên — chưa tốn gì cho đến khi có",
 "models.endpointnote": "Các endpoint nằm dưới [llm.<name>] — omavoi config edit. Khóa "
                        "không bao giờ nằm trong file cấu hình: hãy đặt biến môi trường "
                        "của nó, hoặc để trong secrets.toml.",
 "models.vram": "VRAM · ",
 "models.seg.speech": 'mô hình giọng nói',
 "models.seg.other": 'chương trình khác',
 "models.seg.free": 'còn trống',
 "models.vramsub": "đang dùng trên toàn máy",
 "models.needs": "cần",
 "models.vramnote": "Giữ cả hai thường trú mới là điểm chính: một chuỗi phải nạp trọng số "
                    "mỗi lần ghi sẽ tốn hàng giây, không phải hàng mili giây. Nếu vượt quá "
                    "dung lượng, thứ bị đẩy ra là mô hình giọng nói — việc nhập bằng giọng "
                    "chậm đi mười lần mà không có gì nói cho bạn biết vì sao.",

 "dict.rules": "quy tắc",
 "dict.names": "tên riêng",
 "dict.blurb": "nghe thành → thật ra là. Prompt của bộ giải mã chỉ là gợi ý mà mô hình có "
               "thể bỏ qua; đây mới là thứ bảo đảm. Khóa dài nhất được thử trước, nên một "
               "khóa ngắn hơn nằm bên trong nó sẽ không bao giờ chạy.",
 "dict.shadowed": "không bao giờ chạy — bị che bởi ",
 "dict.remove": "Bỏ",
 "dict.namesblurb": "Chỉ viết dạng đúng. Tên riêng được đưa vào prompt của bộ giải mã để mô "
                    "hình tạo ra chúng, rồi sau đó khớp theo âm để các từ đồng âm quay về "
                    "đúng dạng. Việc khớp vẫn tắt cho đến khi bạn xem một lần chạy thử — "
                    "đây là thứ duy nhất ở đây có thể làm hỏng văn bản vốn đã đúng.",
 "dict.matching": "đang khớp",
 "dict.seedonly": "chỉ đưa vào prompt",
 "dict.dryrun": "Chạy thử",
 "dict.enable": "Bật việc khớp",
 "dict.prompt": "prompt: ",
 "dict.none": "(không có)",
 "dict.addrule": "Thêm một mục với  omavoi dict add <nghe thành> <thật ra là>",
 "dict.addnames": "Thêm nhiều mục một lượt với  omavoi names add <tên> <tên> …",

 "set.ptt": "giữ để nói",
 "set.toggle": "bấm để bật/tắt",
 "set.dwell.always": "luôn luôn",
 "set.dwell.changed": "khi có thay đổi",
 "set.dwell.never": "không bao giờ",
 "set.hotkey": "PHÍM NÓNG",
 "set.key.rebind": 'Bấm một phím',
 "set.key.press": 'đang chờ — bấm ngay',
 "set.key": "phím",
 "set.behaviour": "cách hoạt động",
 "set.key.check": 'Kiểm tra lại',
 "set.key.ok": 'đang nghe trên %1',
 "set.key.testing": 'đang kiểm tra…',
 "set.key.badname": '%1 không phải là phím máy này có — hãy bấm một phím thay vì vậy',
 "set.key.nogroup": 'Bạn không ở trong nhóm `input`, nên không mở được bàn phím nào — '
                    'phím được đọc trực tiếp từ thiết bị, bên dưới màn hình nền',
 "set.key.relogin": 'Bạn đã ở trong nhóm `input`, nhưng phiên này bắt đầu trước đó — '
                    'hãy đăng xuất rồi đăng nhập lại',
 "set.key.nodevice": 'Không bàn phím nào ở đây báo %1 — hãy bấm một phím khác',
 "set.key.stopped": 'Dịch vụ nền không chạy, nên không có gì đang nghe',
 "set.key.stale": 'Dịch vụ vẫn đang nghe trên %1 — nó chưa nhận thay đổi này',
 "set.key.off": 'Phím tắt đang bị tắt',
 "set.key.fix.restart": 'Khởi động lại',
 "set.key.fix.group": 'Thêm tôi vào `input`',
 "set.hotkeynote": "Đọc trực tiếp từ evdev, nằm dưới xkb, nên phím vẫn ở đúng vị trí vật lý "
                   "của nó dù bố cục bàn phím có gán lại. Không thể gán một phím modifier "
                   "trong Hyprland để thay thế: bấm modifier làm modmask đổi, khiến ràng "
                   "buộc lúc nhả phím chạy ngay và ghi ra một bản dài 0,0 giây.",
 "set.audio": "ÂM THANH",
 "set.preroll": "đệm trước",
 "set.prerollwhy": "Phần âm thanh giữ lại từ trước lúc bấm phím. Giảm xuống thì âm tiết đầu "
                   "bắt đầu bị mất trong lúc PipeWire mở luồng.",
 "set.tail": "đệm sau",
 "set.warnbelow": "cảnh báo khi dưới",
 "set.maxtake": "dài nhất mỗi lần",
 "set.hud": "HUD",
 "set.keepup": "giữ kết quả trên màn hình",
 "set.hudnote": "Mặc định là „changed“: một khoảng chờ mà bạn luôn phải trả sẽ thành thứ gây "
                "nhiễu ngay khi bạn đọc hai câu liền nhau, nhưng một lần sửa âm thầm mà bạn "
                "không hề thấy thì tệ hơn.",
 "set.notifications": "thông báo",
 "set.on": "bật",
 "set.off": "tắt",
 "set.history": "LỊCH SỬ",
 "set.keepaudio": "giữ âm thanh cho",
 "set.takes": " bản ghi",
 "set.historynote": "Âm thanh đã lưu là thứ cho phép chạy lại một bản ghi trên mô hình khác, "
                    "và chạy thử phần tên riêng. Đặt về 0 thì cả hai mất theo.",
 "set.privacy": "GIỌNG CỦA BẠN ĐI ĐÂU",
 "set.neverleaves": "Âm thanh không bao giờ rời khỏi máy này",
 "set.privacynote": "Việc nhận dạng giọng nói chạy trên GPU cục bộ ở mọi chế độ. Nhưng chế "
                    "độ nào có bước LLM dùng mô hình từ xa thì đúng là gửi văn bản đã chuyển "
                    "ra ngoài — thẻ Chế độ cho thấy chế độ nào có bước đó.",
 "set.editconfig": "Sửa cấu hình",
 "set.restart": "Khởi động lại dịch vụ",
 "set.configpath": "mọi thứ ở đây nằm trong  ~/.config/omavoi/config.toml",
}
